// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: area.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CragId        int64                  `protobuf:"varint,4,opt,name=crag_id,json=cragId,proto3" json:"crag_id,omitempty"`
	Polygon       *Polygon               `protobuf:"bytes,5,opt,name=polygon,proto3" json:"polygon,omitempty"`
	Boulders      []*Boulder             `protobuf:"bytes,6,rep,name=boulders,proto3" json:"boulders,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,7,rep,name=comments,proto3" json:"comments,omitempty"`
	Photos        []*Photo               `protobuf:"bytes,8,rep,name=photos,proto3" json:"photos,omitempty"`
	Timestamps    *Timestamps            `protobuf:"bytes,9,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_area_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_area_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_area_proto_rawDescGZIP(), []int{0}
}

func (x *Area) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Area) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Area) GetCragId() int64 {
	if x != nil {
		return x.CragId
	}
	return 0
}

func (x *Area) GetPolygon() *Polygon {
	if x != nil {
		return x.Polygon
	}
	return nil
}

func (x *Area) GetBoulders() []*Boulder {
	if x != nil {
		return x.Boulders
	}
	return nil
}

func (x *Area) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *Area) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Area) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

var File_area_proto protoreflect.FileDescriptor

const file_area_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"area.proto\x12\x02pb\x1a\rboulder.proto\x1a\rcomment.proto\x1a\vphoto.proto\x1a\rpolygon.proto\x1a\x10timestamps.proto\"\xb1\x02\n" +
	"\x04Area\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\acrag_id\x18\x04 \x01(\x03R\x06cragId\x12%\n" +
	"\apolygon\x18\x05 \x01(\v2\v.pb.PolygonR\apolygon\x12'\n" +
	"\bboulders\x18\x06 \x03(\v2\v.pb.BoulderR\bboulders\x12'\n" +
	"\bcomments\x18\a \x03(\v2\v.pb.CommentR\bcomments\x12!\n" +
	"\x06photos\x18\b \x03(\v2\t.pb.PhotoR\x06photos\x12.\n" +
	"\n" +
	"timestamps\x18\t \x01(\v2\x0e.pb.TimestampsR\n" +
	"timestampsB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_area_proto_rawDescOnce sync.Once
	file_area_proto_rawDescData []byte
)

func file_area_proto_rawDescGZIP() []byte {
	file_area_proto_rawDescOnce.Do(func() {
		file_area_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_area_proto_rawDesc), len(file_area_proto_rawDesc)))
	})
	return file_area_proto_rawDescData
}

var file_area_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_area_proto_goTypes = []any{
	(*Area)(nil),       // 0: pb.Area
	(*Polygon)(nil),    // 1: pb.Polygon
	(*Boulder)(nil),    // 2: pb.Boulder
	(*Comment)(nil),    // 3: pb.Comment
	(*Photo)(nil),      // 4: pb.Photo
	(*Timestamps)(nil), // 5: pb.Timestamps
}
var file_area_proto_depIdxs = []int32{
	1, // 0: pb.Area.polygon:type_name -> pb.Polygon
	2, // 1: pb.Area.boulders:type_name -> pb.Boulder
	3, // 2: pb.Area.comments:type_name -> pb.Comment
	4, // 3: pb.Area.photos:type_name -> pb.Photo
	5, // 4: pb.Area.timestamps:type_name -> pb.Timestamps
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_area_proto_init() }
func file_area_proto_init() {
	if File_area_proto != nil {
		return
	}
	file_boulder_proto_init()
	file_comment_proto_init()
	file_photo_proto_init()
	file_polygon_proto_init()
	file_timestamps_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_area_proto_rawDesc), len(file_area_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_area_proto_goTypes,
		DependencyIndexes: file_area_proto_depIdxs,
		MessageInfos:      file_area_proto_msgTypes,
	}.Build()
	File_area_proto = out.File
	file_area_proto_goTypes = nil
	file_area_proto_depIdxs = nil
}
