// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: boulder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Boulder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Coordinates   *Coordinate            `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	AreaId        int64                  `protobuf:"varint,5,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Routes        []*Route               `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
	Polygon       *Polygon               `protobuf:"bytes,7,opt,name=polygon,proto3" json:"polygon,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,8,rep,name=comments,proto3" json:"comments,omitempty"`
	Photos        []*Photo               `protobuf:"bytes,9,rep,name=photos,proto3" json:"photos,omitempty"`
	Timestamps    *Timestamps            `protobuf:"bytes,10,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Boulder) Reset() {
	*x = Boulder{}
	mi := &file_boulder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boulder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boulder) ProtoMessage() {}

func (x *Boulder) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boulder.ProtoReflect.Descriptor instead.
func (*Boulder) Descriptor() ([]byte, []int) {
	return file_boulder_proto_rawDescGZIP(), []int{0}
}

func (x *Boulder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Boulder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Boulder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Boulder) GetCoordinates() *Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Boulder) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *Boulder) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Boulder) GetPolygon() *Polygon {
	if x != nil {
		return x.Polygon
	}
	return nil
}

func (x *Boulder) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *Boulder) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Boulder) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

var File_boulder_proto protoreflect.FileDescriptor

const file_boulder_proto_rawDesc = "" +
	"\n" +
	"\rboulder.proto\x12\x02pb\x1a\rcomment.proto\x1a\x10coordinate.proto\x1a\vphoto.proto\x1a\rpolygon.proto\x1a\vroute.proto\x1a\x10timestamps.proto\"\xe0\x02\n" +
	"\aBoulder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\vcoordinates\x18\x04 \x01(\v2\x0e.pb.CoordinateR\vcoordinates\x12\x17\n" +
	"\aarea_id\x18\x05 \x01(\x03R\x06areaId\x12!\n" +
	"\x06routes\x18\x06 \x03(\v2\t.pb.RouteR\x06routes\x12%\n" +
	"\apolygon\x18\a \x01(\v2\v.pb.PolygonR\apolygon\x12'\n" +
	"\bcomments\x18\b \x03(\v2\v.pb.CommentR\bcomments\x12!\n" +
	"\x06photos\x18\t \x03(\v2\t.pb.PhotoR\x06photos\x12.\n" +
	"\n" +
	"timestamps\x18\n" +
	" \x01(\v2\x0e.pb.TimestampsR\n" +
	"timestampsB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_boulder_proto_rawDescOnce sync.Once
	file_boulder_proto_rawDescData []byte
)

func file_boulder_proto_rawDescGZIP() []byte {
	file_boulder_proto_rawDescOnce.Do(func() {
		file_boulder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boulder_proto_rawDesc), len(file_boulder_proto_rawDesc)))
	})
	return file_boulder_proto_rawDescData
}

var file_boulder_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_boulder_proto_goTypes = []any{
	(*Boulder)(nil),    // 0: pb.Boulder
	(*Coordinate)(nil), // 1: pb.Coordinate
	(*Route)(nil),      // 2: pb.Route
	(*Polygon)(nil),    // 3: pb.Polygon
	(*Comment)(nil),    // 4: pb.Comment
	(*Photo)(nil),      // 5: pb.Photo
	(*Timestamps)(nil), // 6: pb.Timestamps
}
var file_boulder_proto_depIdxs = []int32{
	1, // 0: pb.Boulder.coordinates:type_name -> pb.Coordinate
	2, // 1: pb.Boulder.routes:type_name -> pb.Route
	3, // 2: pb.Boulder.polygon:type_name -> pb.Polygon
	4, // 3: pb.Boulder.comments:type_name -> pb.Comment
	5, // 4: pb.Boulder.photos:type_name -> pb.Photo
	6, // 5: pb.Boulder.timestamps:type_name -> pb.Timestamps
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_boulder_proto_init() }
func file_boulder_proto_init() {
	if File_boulder_proto != nil {
		return
	}
	file_comment_proto_init()
	file_coordinate_proto_init()
	file_photo_proto_init()
	file_polygon_proto_init()
	file_route_proto_init()
	file_timestamps_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boulder_proto_rawDesc), len(file_boulder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boulder_proto_goTypes,
		DependencyIndexes: file_boulder_proto_depIdxs,
		MessageInfos:      file_boulder_proto_msgTypes,
	}.Build()
	File_boulder_proto = out.File
	file_boulder_proto_goTypes = nil
	file_boulder_proto_depIdxs = nil
}
