// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bounds.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopLeft       *Coordinate            `protobuf:"bytes,1,opt,name=top_left,json=topLeft,proto3" json:"top_left,omitempty"`
	BottomRight   *Coordinate            `protobuf:"bytes,2,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bounds) Reset() {
	*x = Bounds{}
	mi := &file_bounds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bounds) ProtoMessage() {}

func (x *Bounds) ProtoReflect() protoreflect.Message {
	mi := &file_bounds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bounds.ProtoReflect.Descriptor instead.
func (*Bounds) Descriptor() ([]byte, []int) {
	return file_bounds_proto_rawDescGZIP(), []int{0}
}

func (x *Bounds) GetTopLeft() *Coordinate {
	if x != nil {
		return x.TopLeft
	}
	return nil
}

func (x *Bounds) GetBottomRight() *Coordinate {
	if x != nil {
		return x.BottomRight
	}
	return nil
}

var File_bounds_proto protoreflect.FileDescriptor

const file_bounds_proto_rawDesc = "" +
	"\n" +
	"\fbounds.proto\x12\x02pb\x1a\x10coordinate.proto\"f\n" +
	"\x06Bounds\x12)\n" +
	"\btop_left\x18\x01 \x01(\v2\x0e.pb.CoordinateR\atopLeft\x121\n" +
	"\fbottom_right\x18\x02 \x01(\v2\x0e.pb.CoordinateR\vbottomRightB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_bounds_proto_rawDescOnce sync.Once
	file_bounds_proto_rawDescData []byte
)

func file_bounds_proto_rawDescGZIP() []byte {
	file_bounds_proto_rawDescOnce.Do(func() {
		file_bounds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bounds_proto_rawDesc), len(file_bounds_proto_rawDesc)))
	})
	return file_bounds_proto_rawDescData
}

var file_bounds_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bounds_proto_goTypes = []any{
	(*Bounds)(nil),     // 0: pb.Bounds
	(*Coordinate)(nil), // 1: pb.Coordinate
}
var file_bounds_proto_depIdxs = []int32{
	1, // 0: pb.Bounds.top_left:type_name -> pb.Coordinate
	1, // 1: pb.Bounds.bottom_right:type_name -> pb.Coordinate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bounds_proto_init() }
func file_bounds_proto_init() {
	if File_bounds_proto != nil {
		return
	}
	file_coordinate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bounds_proto_rawDesc), len(file_bounds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bounds_proto_goTypes,
		DependencyIndexes: file_bounds_proto_depIdxs,
		MessageInfos:      file_bounds_proto_msgTypes,
	}.Build()
	File_bounds_proto = out.File
	file_bounds_proto_goTypes = nil
	file_bounds_proto_depIdxs = nil
}
