// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: climb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for entities that can have comments
type CommentableEntityType int32

const (
	CommentableEntityType_COMMENTABLE_ENTITY_TYPE_UNSPECIFIED CommentableEntityType = 0
	CommentableEntityType_COMMENTABLE_ENTITY_TYPE_CRAG        CommentableEntityType = 1
	CommentableEntityType_COMMENTABLE_ENTITY_TYPE_AREA        CommentableEntityType = 2
	CommentableEntityType_COMMENTABLE_ENTITY_TYPE_BOULDER     CommentableEntityType = 3
	CommentableEntityType_COMMENTABLE_ENTITY_TYPE_ROUTE       CommentableEntityType = 4
)

// Enum value maps for CommentableEntityType.
var (
	CommentableEntityType_name = map[int32]string{
		0: "COMMENTABLE_ENTITY_TYPE_UNSPECIFIED",
		1: "COMMENTABLE_ENTITY_TYPE_CRAG",
		2: "COMMENTABLE_ENTITY_TYPE_AREA",
		3: "COMMENTABLE_ENTITY_TYPE_BOULDER",
		4: "COMMENTABLE_ENTITY_TYPE_ROUTE",
	}
	CommentableEntityType_value = map[string]int32{
		"COMMENTABLE_ENTITY_TYPE_UNSPECIFIED": 0,
		"COMMENTABLE_ENTITY_TYPE_CRAG":        1,
		"COMMENTABLE_ENTITY_TYPE_AREA":        2,
		"COMMENTABLE_ENTITY_TYPE_BOULDER":     3,
		"COMMENTABLE_ENTITY_TYPE_ROUTE":       4,
	}
)

func (x CommentableEntityType) Enum() *CommentableEntityType {
	p := new(CommentableEntityType)
	*p = x
	return p
}

func (x CommentableEntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentableEntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_climb_proto_enumTypes[0].Descriptor()
}

func (CommentableEntityType) Type() protoreflect.EnumType {
	return &file_climb_proto_enumTypes[0]
}

func (x CommentableEntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentableEntityType.Descriptor instead.
func (CommentableEntityType) EnumDescriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{0}
}

// Request for GetComments
type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    CommentableEntityType  `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=pb.CommentableEntityType" json:"entity_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_climb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{0}
}

func (x *GetCommentsRequest) GetEntityType() CommentableEntityType {
	if x != nil {
		return x.EntityType
	}
	return CommentableEntityType_COMMENTABLE_ENTITY_TYPE_UNSPECIFIED
}

func (x *GetCommentsRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// Response for GetComments
type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_climb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{1}
}

func (x *GetCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// Request for CreateComment
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    CommentableEntityType  `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=pb.CommentableEntityType" json:"entity_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_climb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentRequest) GetEntityType() CommentableEntityType {
	if x != nil {
		return x.EntityType
	}
	return CommentableEntityType_COMMENTABLE_ENTITY_TYPE_UNSPECIFIED
}

func (x *CreateCommentRequest) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *CreateCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Response for CreateComment
type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_climb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// GetArea
type ReadAreaOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Includes      []string               `protobuf:"bytes,1,rep,name=includes,proto3" json:"includes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAreaOptions) Reset() {
	*x = ReadAreaOptions{}
	mi := &file_climb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAreaOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAreaOptions) ProtoMessage() {}

func (x *ReadAreaOptions) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAreaOptions.ProtoReflect.Descriptor instead.
func (*ReadAreaOptions) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{4}
}

func (x *ReadAreaOptions) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

type GetAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Opts          *ReadAreaOptions       `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAreaRequest) Reset() {
	*x = GetAreaRequest{}
	mi := &file_climb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaRequest) ProtoMessage() {}

func (x *GetAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaRequest.ProtoReflect.Descriptor instead.
func (*GetAreaRequest) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{5}
}

func (x *GetAreaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAreaRequest) GetOpts() *ReadAreaOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type GetAreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Area          *Area                  `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAreaResponse) Reset() {
	*x = GetAreaResponse{}
	mi := &file_climb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaResponse) ProtoMessage() {}

func (x *GetAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaResponse.ProtoReflect.Descriptor instead.
func (*GetAreaResponse) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{6}
}

func (x *GetAreaResponse) GetArea() *Area {
	if x != nil {
		return x.Area
	}
	return nil
}

// UpdateArea
type UpdateAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Polygon       *Polygon               `protobuf:"bytes,5,opt,name=polygon,proto3" json:"polygon,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAreaRequest) Reset() {
	*x = UpdateAreaRequest{}
	mi := &file_climb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaRequest) ProtoMessage() {}

func (x *UpdateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateAreaRequest) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAreaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAreaRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *UpdateAreaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAreaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAreaRequest) GetPolygon() *Polygon {
	if x != nil {
		return x.Polygon
	}
	return nil
}

func (x *UpdateAreaRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type UpdateAreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAreaResponse) Reset() {
	*x = UpdateAreaResponse{}
	mi := &file_climb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaResponse) ProtoMessage() {}

func (x *UpdateAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaResponse.ProtoReflect.Descriptor instead.
func (*UpdateAreaResponse) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{8}
}

// GetCrag
type ReadCragOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Includes      []string               `protobuf:"bytes,1,rep,name=includes,proto3" json:"includes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCragOptions) Reset() {
	*x = ReadCragOptions{}
	mi := &file_climb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCragOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCragOptions) ProtoMessage() {}

func (x *ReadCragOptions) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCragOptions.ProtoReflect.Descriptor instead.
func (*ReadCragOptions) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{9}
}

func (x *ReadCragOptions) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

type GetCragResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crag          *Crag                  `protobuf:"bytes,1,opt,name=crag,proto3" json:"crag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCragResponse) Reset() {
	*x = GetCragResponse{}
	mi := &file_climb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCragResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCragResponse) ProtoMessage() {}

func (x *GetCragResponse) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCragResponse.ProtoReflect.Descriptor instead.
func (*GetCragResponse) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{10}
}

func (x *GetCragResponse) GetCrag() *Crag {
	if x != nil {
		return x.Crag
	}
	return nil
}

type GetCragRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Opts          *ReadCragOptions       `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCragRequest) Reset() {
	*x = GetCragRequest{}
	mi := &file_climb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCragRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCragRequest) ProtoMessage() {}

func (x *GetCragRequest) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCragRequest.ProtoReflect.Descriptor instead.
func (*GetCragRequest) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{11}
}

func (x *GetCragRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCragRequest) GetOpts() *ReadCragOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

// ListCrags
type ListCragsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opts          *ReadCragOptions       `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCragsRequest) Reset() {
	*x = ListCragsRequest{}
	mi := &file_climb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCragsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCragsRequest) ProtoMessage() {}

func (x *ListCragsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCragsRequest.ProtoReflect.Descriptor instead.
func (*ListCragsRequest) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{12}
}

func (x *ListCragsRequest) GetOpts() *ReadCragOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type ListCragsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crags         []*Crag                `protobuf:"bytes,1,rep,name=crags,proto3" json:"crags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCragsResponse) Reset() {
	*x = ListCragsResponse{}
	mi := &file_climb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCragsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCragsResponse) ProtoMessage() {}

func (x *ListCragsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCragsResponse.ProtoReflect.Descriptor instead.
func (*ListCragsResponse) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{13}
}

func (x *ListCragsResponse) GetCrags() []*Crag {
	if x != nil {
		return x.Crags
	}
	return nil
}

// UpdateCrag
type UpdateCragRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Trail         *Trail                 `protobuf:"bytes,5,opt,name=trail,proto3" json:"trail,omitempty"`
	Bounds        *Bounds                `protobuf:"bytes,6,opt,name=bounds,proto3" json:"bounds,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCragRequest) Reset() {
	*x = UpdateCragRequest{}
	mi := &file_climb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCragRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCragRequest) ProtoMessage() {}

func (x *UpdateCragRequest) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCragRequest.ProtoReflect.Descriptor instead.
func (*UpdateCragRequest) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCragRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCragRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *UpdateCragRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCragRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCragRequest) GetTrail() *Trail {
	if x != nil {
		return x.Trail
	}
	return nil
}

func (x *UpdateCragRequest) GetBounds() *Bounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *UpdateCragRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type UpdateCragResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCragResponse) Reset() {
	*x = UpdateCragResponse{}
	mi := &file_climb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCragResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCragResponse) ProtoMessage() {}

func (x *UpdateCragResponse) ProtoReflect() protoreflect.Message {
	mi := &file_climb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCragResponse.ProtoReflect.Descriptor instead.
func (*UpdateCragResponse) Descriptor() ([]byte, []int) {
	return file_climb_proto_rawDescGZIP(), []int{15}
}

var File_climb_proto protoreflect.FileDescriptor

const file_climb_proto_rawDesc = "" +
	"\n" +
	"\vclimb.proto\x12\x02pb\x1a\n" +
	"area.proto\x1a\fbounds.proto\x1a\rcomment.proto\x1a\n" +
	"crag.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rpolygon.proto\x1a\vtrail.proto\"m\n" +
	"\x12GetCommentsRequest\x12:\n" +
	"\ventity_type\x18\x01 \x01(\x0e2\x19.pb.CommentableEntityTypeR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\">\n" +
	"\x13GetCommentsResponse\x12'\n" +
	"\bcomments\x18\x01 \x03(\v2\v.pb.CommentR\bcomments\"\x83\x01\n" +
	"\x14CreateCommentRequest\x12:\n" +
	"\ventity_type\x18\x01 \x01(\x0e2\x19.pb.CommentableEntityTypeR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\x03R\bentityId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\">\n" +
	"\x15CreateCommentResponse\x12%\n" +
	"\acomment\x18\x01 \x01(\v2\v.pb.CommentR\acomment\"-\n" +
	"\x0fReadAreaOptions\x12\x1a\n" +
	"\bincludes\x18\x01 \x03(\tR\bincludes\"I\n" +
	"\x0eGetAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x04opts\x18\x02 \x01(\v2\x13.pb.ReadAreaOptionsR\x04opts\"/\n" +
	"\x0fGetAreaResponse\x12\x1c\n" +
	"\x04area\x18\x01 \x01(\v2\b.pb.AreaR\x04area\"\xfa\x01\n" +
	"\x11UpdateAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12%\n" +
	"\apolygon\x18\x05 \x01(\v2\v.pb.PolygonR\apolygon\x12=\n" +
	"\frequested_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\x14\n" +
	"\x12UpdateAreaResponse\"-\n" +
	"\x0fReadCragOptions\x12\x1a\n" +
	"\bincludes\x18\x01 \x03(\tR\bincludes\"/\n" +
	"\x0fGetCragResponse\x12\x1c\n" +
	"\x04crag\x18\x01 \x01(\v2\b.pb.CragR\x04crag\"I\n" +
	"\x0eGetCragRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x04opts\x18\x02 \x01(\v2\x13.pb.ReadCragOptionsR\x04opts\";\n" +
	"\x10ListCragsRequest\x12'\n" +
	"\x04opts\x18\x02 \x01(\v2\x13.pb.ReadCragOptionsR\x04opts\"3\n" +
	"\x11ListCragsResponse\x12\x1e\n" +
	"\x05crags\x18\x01 \x03(\v2\b.pb.CragR\x05crags\"\x98\x02\n" +
	"\x11UpdateCragRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\x05trail\x18\x05 \x01(\v2\t.pb.TrailR\x05trail\x12\"\n" +
	"\x06bounds\x18\x06 \x01(\v2\n" +
	".pb.BoundsR\x06bounds\x12=\n" +
	"\frequested_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\x14\n" +
	"\x12UpdateCragResponse*\xcc\x01\n" +
	"\x15CommentableEntityType\x12'\n" +
	"#COMMENTABLE_ENTITY_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCOMMENTABLE_ENTITY_TYPE_CRAG\x10\x01\x12 \n" +
	"\x1cCOMMENTABLE_ENTITY_TYPE_AREA\x10\x02\x12#\n" +
	"\x1fCOMMENTABLE_ENTITY_TYPE_BOULDER\x10\x03\x12!\n" +
	"\x1dCOMMENTABLE_ENTITY_TYPE_ROUTE\x10\x042\xb0\x03\n" +
	"\fClimbService\x12D\n" +
	"\rCreateComment\x12\x18.pb.CreateCommentRequest\x1a\x19.pb.CreateCommentResponse\x122\n" +
	"\aGetArea\x12\x12.pb.GetAreaRequest\x1a\x13.pb.GetAreaResponse\x12;\n" +
	"\n" +
	"UpdateArea\x12\x15.pb.UpdateAreaRequest\x1a\x16.pb.UpdateAreaResponse\x122\n" +
	"\aGetCrag\x12\x12.pb.GetCragRequest\x1a\x13.pb.GetCragResponse\x128\n" +
	"\tListCrags\x12\x14.pb.ListCragsRequest\x1a\x15.pb.ListCragsResponse\x12;\n" +
	"\n" +
	"UpdateCrag\x12\x15.pb.UpdateCragRequest\x1a\x16.pb.UpdateCragResponse\x12>\n" +
	"\vGetComments\x12\x16.pb.GetCommentsRequest\x1a\x17.pb.GetCommentsResponseB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_climb_proto_rawDescOnce sync.Once
	file_climb_proto_rawDescData []byte
)

func file_climb_proto_rawDescGZIP() []byte {
	file_climb_proto_rawDescOnce.Do(func() {
		file_climb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_climb_proto_rawDesc), len(file_climb_proto_rawDesc)))
	})
	return file_climb_proto_rawDescData
}

var file_climb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_climb_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_climb_proto_goTypes = []any{
	(CommentableEntityType)(0),    // 0: pb.CommentableEntityType
	(*GetCommentsRequest)(nil),    // 1: pb.GetCommentsRequest
	(*GetCommentsResponse)(nil),   // 2: pb.GetCommentsResponse
	(*CreateCommentRequest)(nil),  // 3: pb.CreateCommentRequest
	(*CreateCommentResponse)(nil), // 4: pb.CreateCommentResponse
	(*ReadAreaOptions)(nil),       // 5: pb.ReadAreaOptions
	(*GetAreaRequest)(nil),        // 6: pb.GetAreaRequest
	(*GetAreaResponse)(nil),       // 7: pb.GetAreaResponse
	(*UpdateAreaRequest)(nil),     // 8: pb.UpdateAreaRequest
	(*UpdateAreaResponse)(nil),    // 9: pb.UpdateAreaResponse
	(*ReadCragOptions)(nil),       // 10: pb.ReadCragOptions
	(*GetCragResponse)(nil),       // 11: pb.GetCragResponse
	(*GetCragRequest)(nil),        // 12: pb.GetCragRequest
	(*ListCragsRequest)(nil),      // 13: pb.ListCragsRequest
	(*ListCragsResponse)(nil),     // 14: pb.ListCragsResponse
	(*UpdateCragRequest)(nil),     // 15: pb.UpdateCragRequest
	(*UpdateCragResponse)(nil),    // 16: pb.UpdateCragResponse
	(*Comment)(nil),               // 17: pb.Comment
	(*Area)(nil),                  // 18: pb.Area
	(*fieldmaskpb.FieldMask)(nil), // 19: google.protobuf.FieldMask
	(*Polygon)(nil),               // 20: pb.Polygon
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*Crag)(nil),                  // 22: pb.Crag
	(*Trail)(nil),                 // 23: pb.Trail
	(*Bounds)(nil),                // 24: pb.Bounds
}
var file_climb_proto_depIdxs = []int32{
	0,  // 0: pb.GetCommentsRequest.entity_type:type_name -> pb.CommentableEntityType
	17, // 1: pb.GetCommentsResponse.comments:type_name -> pb.Comment
	0,  // 2: pb.CreateCommentRequest.entity_type:type_name -> pb.CommentableEntityType
	17, // 3: pb.CreateCommentResponse.comment:type_name -> pb.Comment
	5,  // 4: pb.GetAreaRequest.opts:type_name -> pb.ReadAreaOptions
	18, // 5: pb.GetAreaResponse.area:type_name -> pb.Area
	19, // 6: pb.UpdateAreaRequest.field_mask:type_name -> google.protobuf.FieldMask
	20, // 7: pb.UpdateAreaRequest.polygon:type_name -> pb.Polygon
	21, // 8: pb.UpdateAreaRequest.requested_at:type_name -> google.protobuf.Timestamp
	22, // 9: pb.GetCragResponse.crag:type_name -> pb.Crag
	10, // 10: pb.GetCragRequest.opts:type_name -> pb.ReadCragOptions
	10, // 11: pb.ListCragsRequest.opts:type_name -> pb.ReadCragOptions
	22, // 12: pb.ListCragsResponse.crags:type_name -> pb.Crag
	19, // 13: pb.UpdateCragRequest.field_mask:type_name -> google.protobuf.FieldMask
	23, // 14: pb.UpdateCragRequest.trail:type_name -> pb.Trail
	24, // 15: pb.UpdateCragRequest.bounds:type_name -> pb.Bounds
	21, // 16: pb.UpdateCragRequest.requested_at:type_name -> google.protobuf.Timestamp
	3,  // 17: pb.ClimbService.CreateComment:input_type -> pb.CreateCommentRequest
	6,  // 18: pb.ClimbService.GetArea:input_type -> pb.GetAreaRequest
	8,  // 19: pb.ClimbService.UpdateArea:input_type -> pb.UpdateAreaRequest
	12, // 20: pb.ClimbService.GetCrag:input_type -> pb.GetCragRequest
	13, // 21: pb.ClimbService.ListCrags:input_type -> pb.ListCragsRequest
	15, // 22: pb.ClimbService.UpdateCrag:input_type -> pb.UpdateCragRequest
	1,  // 23: pb.ClimbService.GetComments:input_type -> pb.GetCommentsRequest
	4,  // 24: pb.ClimbService.CreateComment:output_type -> pb.CreateCommentResponse
	7,  // 25: pb.ClimbService.GetArea:output_type -> pb.GetAreaResponse
	9,  // 26: pb.ClimbService.UpdateArea:output_type -> pb.UpdateAreaResponse
	11, // 27: pb.ClimbService.GetCrag:output_type -> pb.GetCragResponse
	14, // 28: pb.ClimbService.ListCrags:output_type -> pb.ListCragsResponse
	16, // 29: pb.ClimbService.UpdateCrag:output_type -> pb.UpdateCragResponse
	2,  // 30: pb.ClimbService.GetComments:output_type -> pb.GetCommentsResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_climb_proto_init() }
func file_climb_proto_init() {
	if File_climb_proto != nil {
		return
	}
	file_area_proto_init()
	file_bounds_proto_init()
	file_comment_proto_init()
	file_crag_proto_init()
	file_polygon_proto_init()
	file_trail_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_climb_proto_rawDesc), len(file_climb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_climb_proto_goTypes,
		DependencyIndexes: file_climb_proto_depIdxs,
		EnumInfos:         file_climb_proto_enumTypes,
		MessageInfos:      file_climb_proto_msgTypes,
	}.Build()
	File_climb_proto = out.File
	file_climb_proto_goTypes = nil
	file_climb_proto_depIdxs = nil
}
