// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: commentable.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commentable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Descriptor_   string                 `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commentable) Reset() {
	*x = Commentable{}
	mi := &file_commentable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commentable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commentable) ProtoMessage() {}

func (x *Commentable) ProtoReflect() protoreflect.Message {
	mi := &file_commentable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commentable.ProtoReflect.Descriptor instead.
func (*Commentable) Descriptor() ([]byte, []int) {
	return file_commentable_proto_rawDescGZIP(), []int{0}
}

func (x *Commentable) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Commentable) GetDescriptor_() string {
	if x != nil {
		return x.Descriptor_
	}
	return ""
}

func (x *Commentable) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_commentable_proto protoreflect.FileDescriptor

const file_commentable_proto_rawDesc = "" +
	"\n" +
	"\x11commentable.proto\x12\x02pb\x1a\rcomment.proto\"f\n" +
	"\vCommentable\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\tR\n" +
	"descriptor\x12'\n" +
	"\bcomments\x18\x03 \x03(\v2\v.pb.CommentR\bcommentsB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_commentable_proto_rawDescOnce sync.Once
	file_commentable_proto_rawDescData []byte
)

func file_commentable_proto_rawDescGZIP() []byte {
	file_commentable_proto_rawDescOnce.Do(func() {
		file_commentable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commentable_proto_rawDesc), len(file_commentable_proto_rawDesc)))
	})
	return file_commentable_proto_rawDescData
}

var file_commentable_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commentable_proto_goTypes = []any{
	(*Commentable)(nil), // 0: pb.Commentable
	(*Comment)(nil),     // 1: pb.Comment
}
var file_commentable_proto_depIdxs = []int32{
	1, // 0: pb.Commentable.comments:type_name -> pb.Comment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commentable_proto_init() }
func file_commentable_proto_init() {
	if File_commentable_proto != nil {
		return
	}
	file_comment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commentable_proto_rawDesc), len(file_commentable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commentable_proto_goTypes,
		DependencyIndexes: file_commentable_proto_depIdxs,
		MessageInfos:      file_commentable_proto_msgTypes,
	}.Build()
	File_commentable_proto = out.File
	file_commentable_proto_goTypes = nil
	file_commentable_proto_depIdxs = nil
}
