// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: coordinate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_coordinate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_coordinate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_coordinate_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinate) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_coordinate_proto protoreflect.FileDescriptor

const file_coordinate_proto_rawDesc = "" +
	"\n" +
	"\x10coordinate.proto\x12\x02pb\"0\n" +
	"\n" +
	"Coordinate\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lngB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_coordinate_proto_rawDescOnce sync.Once
	file_coordinate_proto_rawDescData []byte
)

func file_coordinate_proto_rawDescGZIP() []byte {
	file_coordinate_proto_rawDescOnce.Do(func() {
		file_coordinate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinate_proto_rawDesc), len(file_coordinate_proto_rawDesc)))
	})
	return file_coordinate_proto_rawDescData
}

var file_coordinate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coordinate_proto_goTypes = []any{
	(*Coordinate)(nil), // 0: pb.Coordinate
}
var file_coordinate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coordinate_proto_init() }
func file_coordinate_proto_init() {
	if File_coordinate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinate_proto_rawDesc), len(file_coordinate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coordinate_proto_goTypes,
		DependencyIndexes: file_coordinate_proto_depIdxs,
		MessageInfos:      file_coordinate_proto_msgTypes,
	}.Build()
	File_coordinate_proto = out.File
	file_coordinate_proto_goTypes = nil
	file_coordinate_proto_depIdxs = nil
}
