// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: grade.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Grade_GradingSystem int32

const (
	Grade_GRADING_SYSTEM_UNSPECIFIED Grade_GradingSystem = 0
	Grade_GRADING_SYSTEM_V_SCALE     Grade_GradingSystem = 1
	Grade_GRADING_SYSTEM_YDS         Grade_GradingSystem = 2
)

// Enum value maps for Grade_GradingSystem.
var (
	Grade_GradingSystem_name = map[int32]string{
		0: "GRADING_SYSTEM_UNSPECIFIED",
		1: "GRADING_SYSTEM_V_SCALE",
		2: "GRADING_SYSTEM_YDS",
	}
	Grade_GradingSystem_value = map[string]int32{
		"GRADING_SYSTEM_UNSPECIFIED": 0,
		"GRADING_SYSTEM_V_SCALE":     1,
		"GRADING_SYSTEM_YDS":         2,
	}
)

func (x Grade_GradingSystem) Enum() *Grade_GradingSystem {
	p := new(Grade_GradingSystem)
	*p = x
	return p
}

func (x Grade_GradingSystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grade_GradingSystem) Descriptor() protoreflect.EnumDescriptor {
	return file_grade_proto_enumTypes[0].Descriptor()
}

func (Grade_GradingSystem) Type() protoreflect.EnumType {
	return &file_grade_proto_enumTypes[0]
}

func (x Grade_GradingSystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grade_GradingSystem.Descriptor instead.
func (Grade_GradingSystem) EnumDescriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{0, 0}
}

type Grade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           string                 `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"` // User input string
	System        Grade_GradingSystem    `protobuf:"varint,3,opt,name=system,proto3,enum=pb.Grade_GradingSystem" json:"system,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_grade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_grade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_grade_proto_rawDescGZIP(), []int{0}
}

func (x *Grade) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *Grade) GetSystem() Grade_GradingSystem {
	if x != nil {
		return x.System
	}
	return Grade_GRADING_SYSTEM_UNSPECIFIED
}

func (x *Grade) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_grade_proto protoreflect.FileDescriptor

const file_grade_proto_rawDesc = "" +
	"\n" +
	"\vgrade.proto\x12\x02pb\"\xc5\x01\n" +
	"\x05Grade\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\tR\x03raw\x12/\n" +
	"\x06system\x18\x03 \x01(\x0e2\x17.pb.Grade.GradingSystemR\x06system\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"c\n" +
	"\rGradingSystem\x12\x1e\n" +
	"\x1aGRADING_SYSTEM_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16GRADING_SYSTEM_V_SCALE\x10\x01\x12\x16\n" +
	"\x12GRADING_SYSTEM_YDS\x10\x02B.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_grade_proto_rawDescOnce sync.Once
	file_grade_proto_rawDescData []byte
)

func file_grade_proto_rawDescGZIP() []byte {
	file_grade_proto_rawDescOnce.Do(func() {
		file_grade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grade_proto_rawDesc), len(file_grade_proto_rawDesc)))
	})
	return file_grade_proto_rawDescData
}

var file_grade_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grade_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grade_proto_goTypes = []any{
	(Grade_GradingSystem)(0), // 0: pb.Grade.GradingSystem
	(*Grade)(nil),            // 1: pb.Grade
}
var file_grade_proto_depIdxs = []int32{
	0, // 0: pb.Grade.system:type_name -> pb.Grade.GradingSystem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grade_proto_init() }
func file_grade_proto_init() {
	if File_grade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grade_proto_rawDesc), len(file_grade_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grade_proto_goTypes,
		DependencyIndexes: file_grade_proto_depIdxs,
		EnumInfos:         file_grade_proto_enumTypes,
		MessageInfos:      file_grade_proto_msgTypes,
	}.Build()
	File_grade_proto = out.File
	file_grade_proto_goTypes = nil
	file_grade_proto_depIdxs = nil
}
