// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: line.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Start         *Coordinate            `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *Coordinate            `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"` // Trail trail = 4; // Omitted to avoid circular reference
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_line_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_line_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_line_proto_rawDescGZIP(), []int{0}
}

func (x *Line) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Line) GetStart() *Coordinate {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Line) GetEnd() *Coordinate {
	if x != nil {
		return x.End
	}
	return nil
}

var File_line_proto protoreflect.FileDescriptor

const file_line_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"line.proto\x12\x02pb\x1a\x10coordinate.proto\"^\n" +
	"\x04Line\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\x05start\x18\x02 \x01(\v2\x0e.pb.CoordinateR\x05start\x12 \n" +
	"\x03end\x18\x03 \x01(\v2\x0e.pb.CoordinateR\x03endB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_line_proto_rawDescOnce sync.Once
	file_line_proto_rawDescData []byte
)

func file_line_proto_rawDescGZIP() []byte {
	file_line_proto_rawDescOnce.Do(func() {
		file_line_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_line_proto_rawDesc), len(file_line_proto_rawDesc)))
	})
	return file_line_proto_rawDescData
}

var file_line_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_line_proto_goTypes = []any{
	(*Line)(nil),       // 0: pb.Line
	(*Coordinate)(nil), // 1: pb.Coordinate
}
var file_line_proto_depIdxs = []int32{
	1, // 0: pb.Line.start:type_name -> pb.Coordinate
	1, // 1: pb.Line.end:type_name -> pb.Coordinate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_line_proto_init() }
func file_line_proto_init() {
	if File_line_proto != nil {
		return
	}
	file_coordinate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_line_proto_rawDesc), len(file_line_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_line_proto_goTypes,
		DependencyIndexes: file_line_proto_depIdxs,
		MessageInfos:      file_line_proto_msgTypes,
	}.Build()
	File_line_proto = out.File
	file_line_proto_goTypes = nil
	file_line_proto_depIdxs = nil
}
