// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: parking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      *Coordinate            `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	CragId        int64                  `protobuf:"varint,5,opt,name=crag_id,json=cragId,proto3" json:"crag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parking) Reset() {
	*x = Parking{}
	mi := &file_parking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parking) ProtoMessage() {}

func (x *Parking) ProtoReflect() protoreflect.Message {
	mi := &file_parking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parking.ProtoReflect.Descriptor instead.
func (*Parking) Descriptor() ([]byte, []int) {
	return file_parking_proto_rawDescGZIP(), []int{0}
}

func (x *Parking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Parking) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parking) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parking) GetLocation() *Coordinate {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Parking) GetCragId() int64 {
	if x != nil {
		return x.CragId
	}
	return 0
}

var File_parking_proto protoreflect.FileDescriptor

const file_parking_proto_rawDesc = "" +
	"\n" +
	"\rparking.proto\x12\x02pb\x1a\x10coordinate.proto\"\x94\x01\n" +
	"\aParking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\blocation\x18\x04 \x01(\v2\x0e.pb.CoordinateR\blocation\x12\x17\n" +
	"\acrag_id\x18\x05 \x01(\x03R\x06cragIdB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_parking_proto_rawDescOnce sync.Once
	file_parking_proto_rawDescData []byte
)

func file_parking_proto_rawDescGZIP() []byte {
	file_parking_proto_rawDescOnce.Do(func() {
		file_parking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)))
	})
	return file_parking_proto_rawDescData
}

var file_parking_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parking_proto_goTypes = []any{
	(*Parking)(nil),    // 0: pb.Parking
	(*Coordinate)(nil), // 1: pb.Coordinate
}
var file_parking_proto_depIdxs = []int32{
	1, // 0: pb.Parking.location:type_name -> pb.Coordinate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_parking_proto_init() }
func file_parking_proto_init() {
	if File_parking_proto != nil {
		return
	}
	file_coordinate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parking_proto_rawDesc), len(file_parking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parking_proto_goTypes,
		DependencyIndexes: file_parking_proto_depIdxs,
		MessageInfos:      file_parking_proto_msgTypes,
	}.Build()
	File_parking_proto = out.File
	file_parking_proto_goTypes = nil
	file_parking_proto_depIdxs = nil
}
