// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: photoable.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Photoable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Descriptor_   string                 `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photoable) Reset() {
	*x = Photoable{}
	mi := &file_photoable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photoable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photoable) ProtoMessage() {}

func (x *Photoable) ProtoReflect() protoreflect.Message {
	mi := &file_photoable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photoable.ProtoReflect.Descriptor instead.
func (*Photoable) Descriptor() ([]byte, []int) {
	return file_photoable_proto_rawDescGZIP(), []int{0}
}

func (x *Photoable) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Photoable) GetDescriptor_() string {
	if x != nil {
		return x.Descriptor_
	}
	return ""
}

var File_photoable_proto protoreflect.FileDescriptor

const file_photoable_proto_rawDesc = "" +
	"\n" +
	"\x0fphotoable.proto\x12\x02pb\";\n" +
	"\tPhotoable\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\tR\n" +
	"descriptorB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_photoable_proto_rawDescOnce sync.Once
	file_photoable_proto_rawDescData []byte
)

func file_photoable_proto_rawDescGZIP() []byte {
	file_photoable_proto_rawDescOnce.Do(func() {
		file_photoable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_photoable_proto_rawDesc), len(file_photoable_proto_rawDesc)))
	})
	return file_photoable_proto_rawDescData
}

var file_photoable_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_photoable_proto_goTypes = []any{
	(*Photoable)(nil), // 0: pb.Photoable
}
var file_photoable_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_photoable_proto_init() }
func file_photoable_proto_init() {
	if File_photoable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_photoable_proto_rawDesc), len(file_photoable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_photoable_proto_goTypes,
		DependencyIndexes: file_photoable_proto_depIdxs,
		MessageInfos:      file_photoable_proto_msgTypes,
	}.Build()
	File_photoable_proto = out.File
	file_photoable_proto_goTypes = nil
	file_photoable_proto_depIdxs = nil
}
