// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: photo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Photo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Upload      *Upload                `protobuf:"bytes,4,opt,name=upload,proto3" json:"upload,omitempty"`
	// Topo topo = 5;
	Timestamps    *Timestamps `protobuf:"bytes,6,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_photo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_photo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_photo_proto_rawDescGZIP(), []int{0}
}

func (x *Photo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Photo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Photo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Photo) GetUpload() *Upload {
	if x != nil {
		return x.Upload
	}
	return nil
}

func (x *Photo) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

var File_photo_proto protoreflect.FileDescriptor

const file_photo_proto_rawDesc = "" +
	"\n" +
	"\vphoto.proto\x12\x02pb\x1a\x10timestamps.proto\x1a\fupload.proto\"\xa3\x01\n" +
	"\x05Photo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\x06upload\x18\x04 \x01(\v2\n" +
	".pb.UploadR\x06upload\x12.\n" +
	"\n" +
	"timestamps\x18\x06 \x01(\v2\x0e.pb.TimestampsR\n" +
	"timestampsB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_photo_proto_rawDescOnce sync.Once
	file_photo_proto_rawDescData []byte
)

func file_photo_proto_rawDescGZIP() []byte {
	file_photo_proto_rawDescOnce.Do(func() {
		file_photo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_photo_proto_rawDesc), len(file_photo_proto_rawDesc)))
	})
	return file_photo_proto_rawDescData
}

var file_photo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_photo_proto_goTypes = []any{
	(*Photo)(nil),      // 0: pb.Photo
	(*Upload)(nil),     // 1: pb.Upload
	(*Timestamps)(nil), // 2: pb.Timestamps
}
var file_photo_proto_depIdxs = []int32{
	1, // 0: pb.Photo.upload:type_name -> pb.Upload
	2, // 1: pb.Photo.timestamps:type_name -> pb.Timestamps
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_photo_proto_init() }
func file_photo_proto_init() {
	if File_photo_proto != nil {
		return
	}
	file_timestamps_proto_init()
	file_upload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_photo_proto_rawDesc), len(file_photo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_photo_proto_goTypes,
		DependencyIndexes: file_photo_proto_depIdxs,
		MessageInfos:      file_photo_proto_msgTypes,
	}.Build()
	File_photo_proto = out.File
	file_photo_proto_goTypes = nil
	file_photo_proto_depIdxs = nil
}
