// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: polygon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Descriptor_   string                 `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Coordinates   []*Coordinate          `protobuf:"bytes,3,rep,name=coordinates,proto3" json:"coordinates,omitempty"` // Area area = 4; // Omitted to avoid circular reference
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_polygon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_polygon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_polygon_proto_rawDescGZIP(), []int{0}
}

func (x *Polygon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Polygon) GetDescriptor_() string {
	if x != nil {
		return x.Descriptor_
	}
	return ""
}

func (x *Polygon) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

var File_polygon_proto protoreflect.FileDescriptor

const file_polygon_proto_rawDesc = "" +
	"\n" +
	"\rpolygon.proto\x12\x02pb\x1a\x10coordinate.proto\"k\n" +
	"\aPolygon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\tR\n" +
	"descriptor\x120\n" +
	"\vcoordinates\x18\x03 \x03(\v2\x0e.pb.CoordinateR\vcoordinatesB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_polygon_proto_rawDescOnce sync.Once
	file_polygon_proto_rawDescData []byte
)

func file_polygon_proto_rawDescGZIP() []byte {
	file_polygon_proto_rawDescOnce.Do(func() {
		file_polygon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polygon_proto_rawDesc), len(file_polygon_proto_rawDesc)))
	})
	return file_polygon_proto_rawDescData
}

var file_polygon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_polygon_proto_goTypes = []any{
	(*Polygon)(nil),    // 0: pb.Polygon
	(*Coordinate)(nil), // 1: pb.Coordinate
}
var file_polygon_proto_depIdxs = []int32{
	1, // 0: pb.Polygon.coordinates:type_name -> pb.Coordinate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_polygon_proto_init() }
func file_polygon_proto_init() {
	if File_polygon_proto != nil {
		return
	}
	file_coordinate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polygon_proto_rawDesc), len(file_polygon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polygon_proto_goTypes,
		DependencyIndexes: file_polygon_proto_depIdxs,
		MessageInfos:      file_polygon_proto_msgTypes,
	}.Build()
	File_polygon_proto = out.File
	file_polygon_proto_goTypes = nil
	file_polygon_proto_depIdxs = nil
}
