// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: route.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Route_SizeUnits int32

const (
	Route_SIZE_UNITS_UNSPECIFIED Route_SizeUnits = 0 // Unspecified size units
	Route_SIZE_UNITS_METERS      Route_SizeUnits = 1 // Meters
	Route_SIZE_UNITS_FEET        Route_SizeUnits = 2 // Feet
)

// Enum value maps for Route_SizeUnits.
var (
	Route_SizeUnits_name = map[int32]string{
		0: "SIZE_UNITS_UNSPECIFIED",
		1: "SIZE_UNITS_METERS",
		2: "SIZE_UNITS_FEET",
	}
	Route_SizeUnits_value = map[string]int32{
		"SIZE_UNITS_UNSPECIFIED": 0,
		"SIZE_UNITS_METERS":      1,
		"SIZE_UNITS_FEET":        2,
	}
)

func (x Route_SizeUnits) Enum() *Route_SizeUnits {
	p := new(Route_SizeUnits)
	*p = x
	return p
}

func (x Route_SizeUnits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Route_SizeUnits) Descriptor() protoreflect.EnumDescriptor {
	return file_route_proto_enumTypes[0].Descriptor()
}

func (Route_SizeUnits) Type() protoreflect.EnumType {
	return &file_route_proto_enumTypes[0]
}

func (x Route_SizeUnits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Route_SizeUnits.Descriptor instead.
func (Route_SizeUnits) EnumDescriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{0, 0}
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          *Route_Size            `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	FirstAscent   string                 `protobuf:"bytes,5,opt,name=first_ascent,json=firstAscent,proto3" json:"first_ascent,omitempty"`
	Grade         *Grade                 `protobuf:"bytes,6,opt,name=grade,proto3" json:"grade,omitempty"`
	BoulderId     int64                  `protobuf:"varint,8,opt,name=boulder_id,json=boulderId,proto3" json:"boulder_id,omitempty"`
	Coordinates   *Coordinate            `protobuf:"bytes,9,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Timestamps    *Timestamps            `protobuf:"bytes,10,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetSize() *Route_Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Route) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Route) GetFirstAscent() string {
	if x != nil {
		return x.FirstAscent
	}
	return ""
}

func (x *Route) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

func (x *Route) GetBoulderId() int64 {
	if x != nil {
		return x.BoulderId
	}
	return 0
}

func (x *Route) GetCoordinates() *Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Route) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

// Size specifies the size of the route in whatever dimensions user puts in
type Route_Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         Route_SizeUnits        `protobuf:"varint,1,opt,name=units,proto3,enum=pb.Route_SizeUnits" json:"units,omitempty"` // Units of measurement
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`                       // Height from bottom to top
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`                         // Width from left to right
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route_Size) Reset() {
	*x = Route_Size{}
	mi := &file_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route_Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route_Size) ProtoMessage() {}

func (x *Route_Size) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route_Size.ProtoReflect.Descriptor instead.
func (*Route_Size) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Route_Size) GetUnits() Route_SizeUnits {
	if x != nil {
		return x.Units
	}
	return Route_SIZE_UNITS_UNSPECIFIED
}

func (x *Route_Size) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Route_Size) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

var File_route_proto protoreflect.FileDescriptor

const file_route_proto_rawDesc = "" +
	"\n" +
	"\vroute.proto\x12\x02pb\x1a\x10coordinate.proto\x1a\vgrade.proto\x1a\x10timestamps.proto\"\xec\x03\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04size\x18\x03 \x01(\v2\x0e.pb.Route.SizeR\x04size\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\ffirst_ascent\x18\x05 \x01(\tR\vfirstAscent\x12\x1f\n" +
	"\x05grade\x18\x06 \x01(\v2\t.pb.GradeR\x05grade\x12\x1d\n" +
	"\n" +
	"boulder_id\x18\b \x01(\x03R\tboulderId\x120\n" +
	"\vcoordinates\x18\t \x01(\v2\x0e.pb.CoordinateR\vcoordinates\x12.\n" +
	"\n" +
	"timestamps\x18\n" +
	" \x01(\v2\x0e.pb.TimestampsR\n" +
	"timestamps\x1a_\n" +
	"\x04Size\x12)\n" +
	"\x05units\x18\x01 \x01(\x0e2\x13.pb.Route.SizeUnitsR\x05units\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\"S\n" +
	"\tSizeUnits\x12\x1a\n" +
	"\x16SIZE_UNITS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SIZE_UNITS_METERS\x10\x01\x12\x13\n" +
	"\x0fSIZE_UNITS_FEET\x10\x02B.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_route_proto_rawDescOnce sync.Once
	file_route_proto_rawDescData []byte
)

func file_route_proto_rawDescGZIP() []byte {
	file_route_proto_rawDescOnce.Do(func() {
		file_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_route_proto_rawDesc), len(file_route_proto_rawDesc)))
	})
	return file_route_proto_rawDescData
}

var file_route_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_route_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_route_proto_goTypes = []any{
	(Route_SizeUnits)(0), // 0: pb.Route.SizeUnits
	(*Route)(nil),        // 1: pb.Route
	(*Route_Size)(nil),   // 2: pb.Route.Size
	(*Grade)(nil),        // 3: pb.Grade
	(*Coordinate)(nil),   // 4: pb.Coordinate
	(*Timestamps)(nil),   // 5: pb.Timestamps
}
var file_route_proto_depIdxs = []int32{
	2, // 0: pb.Route.size:type_name -> pb.Route.Size
	3, // 1: pb.Route.grade:type_name -> pb.Grade
	4, // 2: pb.Route.coordinates:type_name -> pb.Coordinate
	5, // 3: pb.Route.timestamps:type_name -> pb.Timestamps
	0, // 4: pb.Route.Size.units:type_name -> pb.Route.SizeUnits
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_route_proto_init() }
func file_route_proto_init() {
	if File_route_proto != nil {
		return
	}
	file_coordinate_proto_init()
	file_grade_proto_init()
	file_timestamps_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_route_proto_rawDesc), len(file_route_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_route_proto_goTypes,
		DependencyIndexes: file_route_proto_depIdxs,
		EnumInfos:         file_route_proto_enumTypes,
		MessageInfos:      file_route_proto_msgTypes,
	}.Build()
	File_route_proto = out.File
	file_route_proto_goTypes = nil
	file_route_proto_depIdxs = nil
}
