// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: timestamps.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamps) Reset() {
	*x = Timestamps{}
	mi := &file_timestamps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps) ProtoMessage() {}

func (x *Timestamps) ProtoReflect() protoreflect.Message {
	mi := &file_timestamps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps.ProtoReflect.Descriptor instead.
func (*Timestamps) Descriptor() ([]byte, []int) {
	return file_timestamps_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamps) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Timestamps) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_timestamps_proto protoreflect.FileDescriptor

const file_timestamps_proto_rawDesc = "" +
	"\n" +
	"\x10timestamps.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n" +
	"\n" +
	"Timestamps\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_timestamps_proto_rawDescOnce sync.Once
	file_timestamps_proto_rawDescData []byte
)

func file_timestamps_proto_rawDescGZIP() []byte {
	file_timestamps_proto_rawDescOnce.Do(func() {
		file_timestamps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timestamps_proto_rawDesc), len(file_timestamps_proto_rawDesc)))
	})
	return file_timestamps_proto_rawDescData
}

var file_timestamps_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_timestamps_proto_goTypes = []any{
	(*Timestamps)(nil),            // 0: pb.Timestamps
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_timestamps_proto_depIdxs = []int32{
	1, // 0: pb.Timestamps.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: pb.Timestamps.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_timestamps_proto_init() }
func file_timestamps_proto_init() {
	if File_timestamps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timestamps_proto_rawDesc), len(file_timestamps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timestamps_proto_goTypes,
		DependencyIndexes: file_timestamps_proto_depIdxs,
		MessageInfos:      file_timestamps_proto_msgTypes,
	}.Build()
	File_timestamps_proto = out.File
	file_timestamps_proto_goTypes = nil
	file_timestamps_proto_depIdxs = nil
}
