// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: topo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Topogons      []*Topogon             `protobuf:"bytes,3,rep,name=topogons,proto3" json:"topogons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topo) Reset() {
	*x = Topo{}
	mi := &file_topo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topo) ProtoMessage() {}

func (x *Topo) ProtoReflect() protoreflect.Message {
	mi := &file_topo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topo.ProtoReflect.Descriptor instead.
func (*Topo) Descriptor() ([]byte, []int) {
	return file_topo_proto_rawDescGZIP(), []int{0}
}

func (x *Topo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Topo) GetTopogons() []*Topogon {
	if x != nil {
		return x.Topogons
	}
	return nil
}

var File_topo_proto protoreflect.FileDescriptor

const file_topo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"topo.proto\x12\x02pb\x1a\rtopogon.proto\"U\n" +
	"\x04Topo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\btopogons\x18\x03 \x03(\v2\v.pb.TopogonR\btopogonsB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_topo_proto_rawDescOnce sync.Once
	file_topo_proto_rawDescData []byte
)

func file_topo_proto_rawDescGZIP() []byte {
	file_topo_proto_rawDescOnce.Do(func() {
		file_topo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topo_proto_rawDesc), len(file_topo_proto_rawDesc)))
	})
	return file_topo_proto_rawDescData
}

var file_topo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_topo_proto_goTypes = []any{
	(*Topo)(nil),    // 0: pb.Topo
	(*Topogon)(nil), // 1: pb.Topogon
}
var file_topo_proto_depIdxs = []int32{
	1, // 0: pb.Topo.topogons:type_name -> pb.Topogon
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_topo_proto_init() }
func file_topo_proto_init() {
	if File_topo_proto != nil {
		return
	}
	file_topogon_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topo_proto_rawDesc), len(file_topo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topo_proto_goTypes,
		DependencyIndexes: file_topo_proto_depIdxs,
		MessageInfos:      file_topo_proto_msgTypes,
	}.Build()
	File_topo_proto = out.File
	file_topo_proto_goTypes = nil
	file_topo_proto_depIdxs = nil
}
