// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: trail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lines         []*Line                `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trail) Reset() {
	*x = Trail{}
	mi := &file_trail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trail) ProtoMessage() {}

func (x *Trail) ProtoReflect() protoreflect.Message {
	mi := &file_trail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trail.ProtoReflect.Descriptor instead.
func (*Trail) Descriptor() ([]byte, []int) {
	return file_trail_proto_rawDescGZIP(), []int{0}
}

func (x *Trail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trail) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_trail_proto protoreflect.FileDescriptor

const file_trail_proto_rawDesc = "" +
	"\n" +
	"\vtrail.proto\x12\x02pb\x1a\n" +
	"line.proto\"7\n" +
	"\x05Trail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\x05lines\x18\x02 \x03(\v2\b.pb.LineR\x05linesB.Z,github.com/greghart/climbing-app/internal/pbb\x06proto3"

var (
	file_trail_proto_rawDescOnce sync.Once
	file_trail_proto_rawDescData []byte
)

func file_trail_proto_rawDescGZIP() []byte {
	file_trail_proto_rawDescOnce.Do(func() {
		file_trail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trail_proto_rawDesc), len(file_trail_proto_rawDesc)))
	})
	return file_trail_proto_rawDescData
}

var file_trail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trail_proto_goTypes = []any{
	(*Trail)(nil), // 0: pb.Trail
	(*Line)(nil),  // 1: pb.Line
}
var file_trail_proto_depIdxs = []int32{
	1, // 0: pb.Trail.lines:type_name -> pb.Line
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trail_proto_init() }
func file_trail_proto_init() {
	if File_trail_proto != nil {
		return
	}
	file_line_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trail_proto_rawDesc), len(file_trail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trail_proto_goTypes,
		DependencyIndexes: file_trail_proto_depIdxs,
		MessageInfos:      file_trail_proto_msgTypes,
	}.Build()
	File_trail_proto = out.File
	file_trail_proto_goTypes = nil
	file_trail_proto_depIdxs = nil
}
