// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file area.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Boulder } from "./boulder_pb";
import { file_boulder } from "./boulder_pb";
import type { Comment } from "./comment_pb";
import { file_comment } from "./comment_pb";
import type { Photo } from "./photo_pb";
import { file_photo } from "./photo_pb";
import type { Polygon } from "./polygon_pb";
import { file_polygon } from "./polygon_pb";
import type { Timestamps } from "./timestamps_pb";
import { file_timestamps } from "./timestamps_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file area.proto.
 */
export const file_area: GenFile = /*@__PURE__*/
  fileDesc("CgphcmVhLnByb3RvEgJwYiLhAQoEQXJlYRIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEg8KB2NyYWdfaWQYBCABKAMSHAoHcG9seWdvbhgFIAEoCzILLnBiLlBvbHlnb24SHQoIYm91bGRlcnMYBiADKAsyCy5wYi5Cb3VsZGVyEh0KCGNvbW1lbnRzGAcgAygLMgsucGIuQ29tbWVudBIZCgZwaG90b3MYCCADKAsyCS5wYi5QaG90bxIiCgp0aW1lc3RhbXBzGAkgASgLMg4ucGIuVGltZXN0YW1wc0IuWixnaXRodWIuY29tL2dyZWdoYXJ0L2NsaW1iaW5nLWFwcC9pbnRlcm5hbC9wYmIGcHJvdG8z", [file_boulder, file_comment, file_photo, file_polygon, file_timestamps]);

/**
 * @generated from message pb.Area
 */
export type Area = Message<"pb.Area"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: int64 crag_id = 4;
   */
  cragId: bigint;

  /**
   * @generated from field: pb.Polygon polygon = 5;
   */
  polygon?: Polygon;

  /**
   * @generated from field: repeated pb.Boulder boulders = 6;
   */
  boulders: Boulder[];

  /**
   * @generated from field: repeated pb.Comment comments = 7;
   */
  comments: Comment[];

  /**
   * @generated from field: repeated pb.Photo photos = 8;
   */
  photos: Photo[];

  /**
   * @generated from field: pb.Timestamps timestamps = 9;
   */
  timestamps?: Timestamps;
};

/**
 * Describes the message pb.Area.
 * Use `create(AreaSchema)` to create a new message.
 */
export const AreaSchema: GenMessage<Area> = /*@__PURE__*/
  messageDesc(file_area, 0);

