// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file area.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Boulder } from "./boulder_pb";
import { file_boulder } from "./boulder_pb";
import type { Commentable } from "./commentable_pb";
import { file_commentable } from "./commentable_pb";
import type { Photoable } from "./photoable_pb";
import { file_photoable } from "./photoable_pb";
import type { Polygon } from "./polygon_pb";
import { file_polygon } from "./polygon_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file area.proto.
 */
export const file_area: GenFile = /*@__PURE__*/
  fileDesc("CgphcmVhLnByb3RvEgJwYiK6AQoEQXJlYRIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhwKB3BvbHlnb24YBSABKAsyCy5wYi5Qb2x5Z29uEh0KCGJvdWxkZXJzGAYgAygLMgsucGIuQm91bGRlchIkCgtjb21tZW50YWJsZRgHIAEoCzIPLnBiLkNvbW1lbnRhYmxlEiAKCXBob3RvYWJsZRgIIAEoCzINLnBiLlBob3RvYWJsZUIuWixnaXRodWIuY29tL2dyZWdoYXJ0L2NsaW1iaW5nLWFwcC9pbnRlcm5hbC9wYmIGcHJvdG8z", [file_boulder, file_commentable, file_photoable, file_polygon]);

/**
 * @generated from message pb.Area
 */
export type Area = Message<"pb.Area"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Crag crag = 4; // Omitted to avoid circular reference
   *
   * @generated from field: pb.Polygon polygon = 5;
   */
  polygon?: Polygon;

  /**
   * @generated from field: repeated pb.Boulder boulders = 6;
   */
  boulders: Boulder[];

  /**
   * @generated from field: pb.Commentable commentable = 7;
   */
  commentable?: Commentable;

  /**
   * @generated from field: pb.Photoable photoable = 8;
   */
  photoable?: Photoable;
};

/**
 * Describes the message pb.Area.
 * Use `create(AreaSchema)` to create a new message.
 */
export const AreaSchema: GenMessage<Area> = /*@__PURE__*/
  messageDesc(file_area, 0);

