// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file boulder.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file boulder.proto.
 */
export const file_boulder: GenFile = /*@__PURE__*/
  fileDesc("Cg1ib3VsZGVyLnByb3RvEgJwYiIVCgdCb3VsZGVyEgoKAmlkGAEgASgDQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM");

/**
 * @generated from message pb.Boulder
 */
export type Boulder = Message<"pb.Boulder"> & {
  /**
   * Add more fields as needed
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message pb.Boulder.
 * Use `create(BoulderSchema)` to create a new message.
 */
export const BoulderSchema: GenMessage<Boulder> = /*@__PURE__*/
  messageDesc(file_boulder, 0);

