// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file climb.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Crag } from "./crag_pb";
import { file_crag } from "./crag_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file climb.proto.
 */
export const file_climb: GenFile = /*@__PURE__*/
  fileDesc("CgtjbGltYi5wcm90bxICcGIiWwoPUmVhZENyYWdPcHRpb25zEhUKDWluY2x1ZGVfYXJlYXMYASABKAgSGAoQaW5jbHVkZV9ib3VsZGVycxgCIAEoCBIXCg9pbmNsdWRlX3BhcmtpbmcYAyABKAgiPwoOR2V0Q3JhZ1JlcXVlc3QSCgoCaWQYASABKAMSIQoEb3B0cxgCIAEoCzITLnBiLlJlYWRDcmFnT3B0aW9ucyIpCg9HZXRDcmFnUmVzcG9uc2USFgoEY3JhZxgBIAEoCzIILnBiLkNyYWciNAoPR2V0Q3JhZ3NSZXF1ZXN0EiEKBG9wdHMYAiABKAsyEy5wYi5SZWFkQ3JhZ09wdGlvbnMiKwoQR2V0Q3JhZ3NSZXNwb25zZRIXCgVjcmFncxgBIAMoCzIILnBiLkNyYWcyeQoMQ2xpbWJTZXJ2aWNlEjIKB0dldENyYWcSEi5wYi5HZXRDcmFnUmVxdWVzdBoTLnBiLkdldENyYWdSZXNwb25zZRI1CghHZXRDcmFncxITLnBiLkdldENyYWdzUmVxdWVzdBoULnBiLkdldENyYWdzUmVzcG9uc2VCLlosZ2l0aHViLmNvbS9ncmVnaGFydC9jbGltYmluZy1hcHAvaW50ZXJuYWwvcGJiBnByb3RvMw", [file_crag]);

/**
 * @generated from message pb.ReadCragOptions
 */
export type ReadCragOptions = Message<"pb.ReadCragOptions"> & {
  /**
   * @generated from field: bool include_areas = 1;
   */
  includeAreas: boolean;

  /**
   * @generated from field: bool include_boulders = 2;
   */
  includeBoulders: boolean;

  /**
   * @generated from field: bool include_parking = 3;
   */
  includeParking: boolean;
};

/**
 * Describes the message pb.ReadCragOptions.
 * Use `create(ReadCragOptionsSchema)` to create a new message.
 */
export const ReadCragOptionsSchema: GenMessage<ReadCragOptions> = /*@__PURE__*/
  messageDesc(file_climb, 0);

/**
 * @generated from message pb.GetCragRequest
 */
export type GetCragRequest = Message<"pb.GetCragRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: pb.ReadCragOptions opts = 2;
   */
  opts?: ReadCragOptions;
};

/**
 * Describes the message pb.GetCragRequest.
 * Use `create(GetCragRequestSchema)` to create a new message.
 */
export const GetCragRequestSchema: GenMessage<GetCragRequest> = /*@__PURE__*/
  messageDesc(file_climb, 1);

/**
 * @generated from message pb.GetCragResponse
 */
export type GetCragResponse = Message<"pb.GetCragResponse"> & {
  /**
   * @generated from field: pb.Crag crag = 1;
   */
  crag?: Crag;
};

/**
 * Describes the message pb.GetCragResponse.
 * Use `create(GetCragResponseSchema)` to create a new message.
 */
export const GetCragResponseSchema: GenMessage<GetCragResponse> = /*@__PURE__*/
  messageDesc(file_climb, 2);

/**
 * @generated from message pb.GetCragsRequest
 */
export type GetCragsRequest = Message<"pb.GetCragsRequest"> & {
  /**
   * @generated from field: pb.ReadCragOptions opts = 2;
   */
  opts?: ReadCragOptions;
};

/**
 * Describes the message pb.GetCragsRequest.
 * Use `create(GetCragsRequestSchema)` to create a new message.
 */
export const GetCragsRequestSchema: GenMessage<GetCragsRequest> = /*@__PURE__*/
  messageDesc(file_climb, 3);

/**
 * @generated from message pb.GetCragsResponse
 */
export type GetCragsResponse = Message<"pb.GetCragsResponse"> & {
  /**
   * @generated from field: repeated pb.Crag crags = 1;
   */
  crags: Crag[];
};

/**
 * Describes the message pb.GetCragsResponse.
 * Use `create(GetCragsResponseSchema)` to create a new message.
 */
export const GetCragsResponseSchema: GenMessage<GetCragsResponse> = /*@__PURE__*/
  messageDesc(file_climb, 4);

/**
 * @generated from service pb.ClimbService
 */
export const ClimbService: GenService<{
  /**
   * @generated from rpc pb.ClimbService.GetCrag
   */
  getCrag: {
    methodKind: "unary";
    input: typeof GetCragRequestSchema;
    output: typeof GetCragResponseSchema;
  },
  /**
   * @generated from rpc pb.ClimbService.GetCrags
   */
  getCrags: {
    methodKind: "unary";
    input: typeof GetCragsRequestSchema;
    output: typeof GetCragsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_climb, 0);

