// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file climb.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Crag } from "./crag_pb";
import { file_crag } from "./crag_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file climb.proto.
 */
export const file_climb: GenFile = /*@__PURE__*/
  fileDesc("CgtjbGltYi5wcm90bxICcGIiIwoPUmVhZENyYWdPcHRpb25zEhAKCGluY2x1ZGVzGAEgAygJIj8KDkdldENyYWdSZXF1ZXN0EgoKAmlkGAEgASgDEiEKBG9wdHMYAiABKAsyEy5wYi5SZWFkQ3JhZ09wdGlvbnMiKQoPR2V0Q3JhZ1Jlc3BvbnNlEhYKBGNyYWcYASABKAsyCC5wYi5DcmFnIjQKD0dldENyYWdzUmVxdWVzdBIhCgRvcHRzGAIgASgLMhMucGIuUmVhZENyYWdPcHRpb25zIisKEEdldENyYWdzUmVzcG9uc2USFwoFY3JhZ3MYASADKAsyCC5wYi5DcmFnMnkKDENsaW1iU2VydmljZRIyCgdHZXRDcmFnEhIucGIuR2V0Q3JhZ1JlcXVlc3QaEy5wYi5HZXRDcmFnUmVzcG9uc2USNQoIR2V0Q3JhZ3MSEy5wYi5HZXRDcmFnc1JlcXVlc3QaFC5wYi5HZXRDcmFnc1Jlc3BvbnNlQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM", [file_crag]);

/**
 * @generated from message pb.ReadCragOptions
 */
export type ReadCragOptions = Message<"pb.ReadCragOptions"> & {
  /**
   * @generated from field: repeated string includes = 1;
   */
  includes: string[];
};

/**
 * Describes the message pb.ReadCragOptions.
 * Use `create(ReadCragOptionsSchema)` to create a new message.
 */
export const ReadCragOptionsSchema: GenMessage<ReadCragOptions> = /*@__PURE__*/
  messageDesc(file_climb, 0);

/**
 * @generated from message pb.GetCragRequest
 */
export type GetCragRequest = Message<"pb.GetCragRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: pb.ReadCragOptions opts = 2;
   */
  opts?: ReadCragOptions;
};

/**
 * Describes the message pb.GetCragRequest.
 * Use `create(GetCragRequestSchema)` to create a new message.
 */
export const GetCragRequestSchema: GenMessage<GetCragRequest> = /*@__PURE__*/
  messageDesc(file_climb, 1);

/**
 * @generated from message pb.GetCragResponse
 */
export type GetCragResponse = Message<"pb.GetCragResponse"> & {
  /**
   * @generated from field: pb.Crag crag = 1;
   */
  crag?: Crag;
};

/**
 * Describes the message pb.GetCragResponse.
 * Use `create(GetCragResponseSchema)` to create a new message.
 */
export const GetCragResponseSchema: GenMessage<GetCragResponse> = /*@__PURE__*/
  messageDesc(file_climb, 2);

/**
 * @generated from message pb.GetCragsRequest
 */
export type GetCragsRequest = Message<"pb.GetCragsRequest"> & {
  /**
   * @generated from field: pb.ReadCragOptions opts = 2;
   */
  opts?: ReadCragOptions;
};

/**
 * Describes the message pb.GetCragsRequest.
 * Use `create(GetCragsRequestSchema)` to create a new message.
 */
export const GetCragsRequestSchema: GenMessage<GetCragsRequest> = /*@__PURE__*/
  messageDesc(file_climb, 3);

/**
 * @generated from message pb.GetCragsResponse
 */
export type GetCragsResponse = Message<"pb.GetCragsResponse"> & {
  /**
   * @generated from field: repeated pb.Crag crags = 1;
   */
  crags: Crag[];
};

/**
 * Describes the message pb.GetCragsResponse.
 * Use `create(GetCragsResponseSchema)` to create a new message.
 */
export const GetCragsResponseSchema: GenMessage<GetCragsResponse> = /*@__PURE__*/
  messageDesc(file_climb, 4);

/**
 * @generated from service pb.ClimbService
 */
export const ClimbService: GenService<{
  /**
   * @generated from rpc pb.ClimbService.GetCrag
   */
  getCrag: {
    methodKind: "unary";
    input: typeof GetCragRequestSchema;
    output: typeof GetCragResponseSchema;
  },
  /**
   * @generated from rpc pb.ClimbService.GetCrags
   */
  getCrags: {
    methodKind: "unary";
    input: typeof GetCragsRequestSchema;
    output: typeof GetCragsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_climb, 0);

