// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file comment.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file comment.proto.
 */
export const file_comment: GenFile = /*@__PURE__*/
  fileDesc("Cg1jb21tZW50LnByb3RvEgJwYiIVCgdDb21tZW50EgoKAmlkGAEgASgDQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM");

/**
 * @generated from message pb.Comment
 */
export type Comment = Message<"pb.Comment"> & {
  /**
   * Add more fields as needed
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message pb.Comment.
 * Use `create(CommentSchema)` to create a new message.
 */
export const CommentSchema: GenMessage<Comment> = /*@__PURE__*/
  messageDesc(file_comment, 0);

