// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file crag.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Area } from "./area_pb";
import { file_area } from "./area_pb";
import type { Bounds } from "./bounds_pb";
import { file_bounds } from "./bounds_pb";
import type { Commentable } from "./commentable_pb";
import { file_commentable } from "./commentable_pb";
import type { Coordinate } from "./coordinate_pb";
import { file_coordinate } from "./coordinate_pb";
import type { Parking } from "./parking_pb";
import { file_parking } from "./parking_pb";
import type { Photoable } from "./photoable_pb";
import { file_photoable } from "./photoable_pb";
import type { Trail } from "./trail_pb";
import { file_trail } from "./trail_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file crag.proto.
 */
export const file_crag: GenFile = /*@__PURE__*/
  fileDesc("CgpjcmFnLnByb3RvEgJwYiLEAgoEQ3JhZxIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhoKBmJvdW5kcxgEIAEoCzIKLnBiLkJvdW5kcxIeCgZjZW50ZXIYBSABKAsyDi5wYi5Db29yZGluYXRlEhQKDGRlZmF1bHRfem9vbRgGIAEoBRIQCghtaW5fem9vbRgHIAEoBRIQCghtYXhfem9vbRgIIAEoBRIcCgdwYXJraW5nGAkgASgLMgsucGIuUGFya2luZxIXCgVhcmVhcxgKIAMoCzIILnBiLkFyZWESJAoLY29tbWVudGFibGUYCyABKAsyDy5wYi5Db21tZW50YWJsZRIgCglwaG90b2FibGUYDCABKAsyDS5wYi5QaG90b2FibGUSGAoFdHJhaWwYDSABKAsyCS5wYi5UcmFpbEIuWixnaXRodWIuY29tL2dyZWdoYXJ0L2NsaW1iaW5nLWFwcC9pbnRlcm5hbC9wYmIGcHJvdG8z", [file_area, file_bounds, file_commentable, file_coordinate, file_parking, file_photoable, file_trail]);

/**
 * @generated from message pb.Crag
 */
export type Crag = Message<"pb.Crag"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: pb.Bounds bounds = 4;
   */
  bounds?: Bounds;

  /**
   * @generated from field: pb.Coordinate center = 5;
   */
  center?: Coordinate;

  /**
   * @generated from field: int32 default_zoom = 6;
   */
  defaultZoom: number;

  /**
   * @generated from field: int32 min_zoom = 7;
   */
  minZoom: number;

  /**
   * @generated from field: int32 max_zoom = 8;
   */
  maxZoom: number;

  /**
   * @generated from field: pb.Parking parking = 9;
   */
  parking?: Parking;

  /**
   * @generated from field: repeated pb.Area areas = 10;
   */
  areas: Area[];

  /**
   * @generated from field: pb.Commentable commentable = 11;
   */
  commentable?: Commentable;

  /**
   * @generated from field: pb.Photoable photoable = 12;
   */
  photoable?: Photoable;

  /**
   * @generated from field: pb.Trail trail = 13;
   */
  trail?: Trail;
};

/**
 * Describes the message pb.Crag.
 * Use `create(CragSchema)` to create a new message.
 */
export const CragSchema: GenMessage<Crag> = /*@__PURE__*/
  messageDesc(file_crag, 0);

