// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file crag.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Area } from "./area_pb";
import { file_area } from "./area_pb";
import type { Bounds } from "./bounds_pb";
import { file_bounds } from "./bounds_pb";
import type { Comment } from "./comment_pb";
import { file_comment } from "./comment_pb";
import type { Coordinate } from "./coordinate_pb";
import { file_coordinate } from "./coordinate_pb";
import type { Parking } from "./parking_pb";
import { file_parking } from "./parking_pb";
import type { Photo } from "./photo_pb";
import { file_photo } from "./photo_pb";
import type { Timestamps } from "./timestamps_pb";
import { file_timestamps } from "./timestamps_pb";
import type { Trail } from "./trail_pb";
import { file_trail } from "./trail_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file crag.proto.
 */
export const file_crag: GenFile = /*@__PURE__*/
  fileDesc("CgpjcmFnLnByb3RvEgJwYiLaAgoEQ3JhZxIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhoKBmJvdW5kcxgEIAEoCzIKLnBiLkJvdW5kcxIeCgZjZW50ZXIYBSABKAsyDi5wYi5Db29yZGluYXRlEhQKDGRlZmF1bHRfem9vbRgGIAEoBRIQCghtaW5fem9vbRgHIAEoBRIQCghtYXhfem9vbRgIIAEoBRIcCgdwYXJraW5nGAkgASgLMgsucGIuUGFya2luZxIXCgVhcmVhcxgKIAMoCzIILnBiLkFyZWESHQoIY29tbWVudHMYCyADKAsyCy5wYi5Db21tZW50EhkKBnBob3RvcxgMIAMoCzIJLnBiLlBob3RvEhgKBXRyYWlsGA0gASgLMgkucGIuVHJhaWwSIgoKdGltZXN0YW1wcxgOIAEoCzIOLnBiLlRpbWVzdGFtcHNCLlosZ2l0aHViLmNvbS9ncmVnaGFydC9jbGltYmluZy1hcHAvaW50ZXJuYWwvcGJiBnByb3RvMw", [file_area, file_bounds, file_comment, file_coordinate, file_parking, file_photo, file_timestamps, file_trail]);

/**
 * @generated from message pb.Crag
 */
export type Crag = Message<"pb.Crag"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: pb.Bounds bounds = 4;
   */
  bounds?: Bounds;

  /**
   * @generated from field: pb.Coordinate center = 5;
   */
  center?: Coordinate;

  /**
   * @generated from field: int32 default_zoom = 6;
   */
  defaultZoom: number;

  /**
   * @generated from field: int32 min_zoom = 7;
   */
  minZoom: number;

  /**
   * @generated from field: int32 max_zoom = 8;
   */
  maxZoom: number;

  /**
   * @generated from field: pb.Parking parking = 9;
   */
  parking?: Parking;

  /**
   * @generated from field: repeated pb.Area areas = 10;
   */
  areas: Area[];

  /**
   * @generated from field: repeated pb.Comment comments = 11;
   */
  comments: Comment[];

  /**
   * @generated from field: repeated pb.Photo photos = 12;
   */
  photos: Photo[];

  /**
   * @generated from field: pb.Trail trail = 13;
   */
  trail?: Trail;

  /**
   * @generated from field: pb.Timestamps timestamps = 14;
   */
  timestamps?: Timestamps;
};

/**
 * Describes the message pb.Crag.
 * Use `create(CragSchema)` to create a new message.
 */
export const CragSchema: GenMessage<Crag> = /*@__PURE__*/
  messageDesc(file_crag, 0);

