// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file grade.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file grade.proto.
 */
export const file_grade: GenFile = /*@__PURE__*/
  fileDesc("CgtncmFkZS5wcm90bxICcGIisQEKBUdyYWRlEgsKA3JhdxgCIAEoCRInCgZzeXN0ZW0YAyABKA4yFy5wYi5HcmFkZS5HcmFkaW5nU3lzdGVtEg0KBXZhbHVlGAQgASgBImMKDUdyYWRpbmdTeXN0ZW0SHgoaR1JBRElOR19TWVNURU1fVU5TUEVDSUZJRUQQABIaChZHUkFESU5HX1NZU1RFTV9WX1NDQUxFEAESFgoSR1JBRElOR19TWVNURU1fWURTEAJCLlosZ2l0aHViLmNvbS9ncmVnaGFydC9jbGltYmluZy1hcHAvaW50ZXJuYWwvcGJiBnByb3RvMw");

/**
 * @generated from message pb.Grade
 */
export type Grade = Message<"pb.Grade"> & {
  /**
   * User input string
   *
   * @generated from field: string raw = 2;
   */
  raw: string;

  /**
   * @generated from field: pb.Grade.GradingSystem system = 3;
   */
  system: Grade_GradingSystem;

  /**
   * @generated from field: double value = 4;
   */
  value: number;
};

/**
 * Describes the message pb.Grade.
 * Use `create(GradeSchema)` to create a new message.
 */
export const GradeSchema: GenMessage<Grade> = /*@__PURE__*/
  messageDesc(file_grade, 0);

/**
 * @generated from enum pb.Grade.GradingSystem
 */
export enum Grade_GradingSystem {
  /**
   * @generated from enum value: GRADING_SYSTEM_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GRADING_SYSTEM_V_SCALE = 1;
   */
  V_SCALE = 1,

  /**
   * @generated from enum value: GRADING_SYSTEM_YDS = 2;
   */
  YDS = 2,
}

/**
 * Describes the enum pb.Grade.GradingSystem.
 */
export const Grade_GradingSystemSchema: GenEnum<Grade_GradingSystem> = /*@__PURE__*/
  enumDesc(file_grade, 0, 0);

