// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file line.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Coordinate } from "./coordinate_pb";
import { file_coordinate } from "./coordinate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file line.proto.
 */
export const file_line: GenFile = /*@__PURE__*/
  fileDesc("CgpsaW5lLnByb3RvEgJwYiJgCgRMaW5lEgoKAmlkGAEgASgDEh0KBXN0YXJ0GAIgASgLMg4ucGIuQ29vcmRpbmF0ZRIbCgNlbmQYAyABKAsyDi5wYi5Db29yZGluYXRlEhAKCHRyYWlsX2lkGAQgASgDQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM", [file_coordinate]);

/**
 * @generated from message pb.Line
 */
export type Line = Message<"pb.Line"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: pb.Coordinate start = 2;
   */
  start?: Coordinate;

  /**
   * @generated from field: pb.Coordinate end = 3;
   */
  end?: Coordinate;

  /**
   * @generated from field: int64 trail_id = 4;
   */
  trailId: bigint;
};

/**
 * Describes the message pb.Line.
 * Use `create(LineSchema)` to create a new message.
 */
export const LineSchema: GenMessage<Line> = /*@__PURE__*/
  messageDesc(file_line, 0);

