// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file parking.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Coordinate } from "./coordinate_pb";
import { file_coordinate } from "./coordinate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file parking.proto.
 */
export const file_parking: GenFile = /*@__PURE__*/
  fileDesc("Cg1wYXJraW5nLnByb3RvEgJwYiJrCgdQYXJraW5nEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSIAoIbG9jYXRpb24YBCABKAsyDi5wYi5Db29yZGluYXRlEg8KB2NyYWdfaWQYBSABKANCLlosZ2l0aHViLmNvbS9ncmVnaGFydC9jbGltYmluZy1hcHAvaW50ZXJuYWwvcGJiBnByb3RvMw", [file_coordinate]);

/**
 * @generated from message pb.Parking
 */
export type Parking = Message<"pb.Parking"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: pb.Coordinate location = 4;
   */
  location?: Coordinate;

  /**
   * @generated from field: int64 crag_id = 5;
   */
  cragId: bigint;
};

/**
 * Describes the message pb.Parking.
 * Use `create(ParkingSchema)` to create a new message.
 */
export const ParkingSchema: GenMessage<Parking> = /*@__PURE__*/
  messageDesc(file_parking, 0);

