// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file photo.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamps } from "./timestamps_pb";
import { file_timestamps } from "./timestamps_pb";
import type { Upload } from "./upload_pb";
import { file_upload } from "./upload_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file photo.proto.
 */
export const file_photo: GenFile = /*@__PURE__*/
  fileDesc("CgtwaG90by5wcm90bxICcGIidwoFUGhvdG8SCgoCaWQYASABKAMSDQoFdGl0bGUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSGgoGdXBsb2FkGAQgASgLMgoucGIuVXBsb2FkEiIKCnRpbWVzdGFtcHMYBiABKAsyDi5wYi5UaW1lc3RhbXBzQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM", [file_timestamps, file_upload]);

/**
 * @generated from message pb.Photo
 */
export type Photo = Message<"pb.Photo"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: pb.Upload upload = 4;
   */
  upload?: Upload;

  /**
   * Topo topo = 5;
   *
   * @generated from field: pb.Timestamps timestamps = 6;
   */
  timestamps?: Timestamps;
};

/**
 * Describes the message pb.Photo.
 * Use `create(PhotoSchema)` to create a new message.
 */
export const PhotoSchema: GenMessage<Photo> = /*@__PURE__*/
  messageDesc(file_photo, 0);

