// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file polygon.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Coordinate } from "./coordinate_pb";
import { file_coordinate } from "./coordinate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file polygon.proto.
 */
export const file_polygon: GenFile = /*@__PURE__*/
  fileDesc("Cg1wb2x5Z29uLnByb3RvEgJwYiJOCgdQb2x5Z29uEgoKAmlkGAEgASgDEhIKCmRlc2NyaXB0b3IYAiABKAkSIwoLY29vcmRpbmF0ZXMYAyADKAsyDi5wYi5Db29yZGluYXRlQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM", [file_coordinate]);

/**
 * @generated from message pb.Polygon
 */
export type Polygon = Message<"pb.Polygon"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string descriptor = 2;
   */
  descriptor: string;

  /**
   * Area area = 4; // Omitted to avoid circular reference
   *
   * @generated from field: repeated pb.Coordinate coordinates = 3;
   */
  coordinates: Coordinate[];
};

/**
 * Describes the message pb.Polygon.
 * Use `create(PolygonSchema)` to create a new message.
 */
export const PolygonSchema: GenMessage<Polygon> = /*@__PURE__*/
  messageDesc(file_polygon, 0);

