// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file polygon_coordinate.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Coordinate } from "./coordinate_pb";
import { file_coordinate } from "./coordinate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file polygon_coordinate.proto.
 */
export const file_polygon_coordinate: GenFile = /*@__PURE__*/
  fileDesc("Chhwb2x5Z29uX2Nvb3JkaW5hdGUucHJvdG8SAnBiIlMKEVBvbHlnb25Db29yZGluYXRlEgoKAmlkGAEgASgDEg0KBW9yZGVyGAIgASgDEiMKC2Nvb3JkaW5hdGVzGAMgASgLMg4ucGIuQ29vcmRpbmF0ZUIuWixnaXRodWIuY29tL2dyZWdoYXJ0L2NsaW1iaW5nLWFwcC9pbnRlcm5hbC9wYmIGcHJvdG8z", [file_coordinate]);

/**
 * @generated from message pb.PolygonCoordinate
 */
export type PolygonCoordinate = Message<"pb.PolygonCoordinate"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 order = 2;
   */
  order: bigint;

  /**
   * @generated from field: pb.Coordinate coordinates = 3;
   */
  coordinates?: Coordinate;
};

/**
 * Describes the message pb.PolygonCoordinate.
 * Use `create(PolygonCoordinateSchema)` to create a new message.
 */
export const PolygonCoordinateSchema: GenMessage<PolygonCoordinate> = /*@__PURE__*/
  messageDesc(file_polygon_coordinate, 0);

