// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file route.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Coordinate } from "./coordinate_pb";
import { file_coordinate } from "./coordinate_pb";
import type { Grade } from "./grade_pb";
import { file_grade } from "./grade_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file route.proto.
 */
export const file_route: GenFile = /*@__PURE__*/
  fileDesc("Cgtyb3V0ZS5wcm90bxICcGIi3QIKBVJvdXRlEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSHAoEc2l6ZRgDIAEoCzIOLnBiLlJvdXRlLlNpemUSEwoLZGVzY3JpcHRpb24YBCABKAkSFAoMZmlyc3RfYXNjZW50GAUgASgJEhgKBWdyYWRlGAYgASgLMgkucGIuR3JhZGUSEgoKYm91bGRlcl9pZBgIIAEoAxIjCgtjb29yZGluYXRlcxgJIAEoCzIOLnBiLkNvb3JkaW5hdGUaSQoEU2l6ZRIiCgV1bml0cxgBIAEoDjITLnBiLlJvdXRlLlNpemVVbml0cxIOCgZoZWlnaHQYAiABKAUSDQoFd2lkdGgYAyABKAUiUwoJU2l6ZVVuaXRzEhoKFlNJWkVfVU5JVFNfVU5TUEVDSUZJRUQQABIVChFTSVpFX1VOSVRTX01FVEVSUxABEhMKD1NJWkVfVU5JVFNfRkVFVBACQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM", [file_coordinate, file_grade]);

/**
 * @generated from message pb.Route
 */
export type Route = Message<"pb.Route"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: pb.Route.Size size = 3;
   */
  size?: Route_Size;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: string first_ascent = 5;
   */
  firstAscent: string;

  /**
   * @generated from field: pb.Grade grade = 6;
   */
  grade?: Grade;

  /**
   * @generated from field: int64 boulder_id = 8;
   */
  boulderId: bigint;

  /**
   * @generated from field: pb.Coordinate coordinates = 9;
   */
  coordinates?: Coordinate;
};

/**
 * Describes the message pb.Route.
 * Use `create(RouteSchema)` to create a new message.
 */
export const RouteSchema: GenMessage<Route> = /*@__PURE__*/
  messageDesc(file_route, 0);

/**
 * Size specifies the size of the route in whatever dimensions user puts in
 *
 * @generated from message pb.Route.Size
 */
export type Route_Size = Message<"pb.Route.Size"> & {
  /**
   * Units of measurement
   *
   * @generated from field: pb.Route.SizeUnits units = 1;
   */
  units: Route_SizeUnits;

  /**
   * Height from bottom to top
   *
   * @generated from field: int32 height = 2;
   */
  height: number;

  /**
   * Width from left to right
   *
   * @generated from field: int32 width = 3;
   */
  width: number;
};

/**
 * Describes the message pb.Route.Size.
 * Use `create(Route_SizeSchema)` to create a new message.
 */
export const Route_SizeSchema: GenMessage<Route_Size> = /*@__PURE__*/
  messageDesc(file_route, 0, 0);

/**
 * @generated from enum pb.Route.SizeUnits
 */
export enum Route_SizeUnits {
  /**
   * Unspecified size units
   *
   * @generated from enum value: SIZE_UNITS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Meters
   *
   * @generated from enum value: SIZE_UNITS_METERS = 1;
   */
  METERS = 1,

  /**
   * Feet
   *
   * @generated from enum value: SIZE_UNITS_FEET = 2;
   */
  FEET = 2,
}

/**
 * Describes the enum pb.Route.SizeUnits.
 */
export const Route_SizeUnitsSchema: GenEnum<Route_SizeUnits> = /*@__PURE__*/
  enumDesc(file_route, 0, 0);

