// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file timestamps.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file timestamps.proto.
 */
export const file_timestamps: GenFile = /*@__PURE__*/
  fileDesc("ChB0aW1lc3RhbXBzLnByb3RvEgJwYiJsCgpUaW1lc3RhbXBzEi4KCmNyZWF0ZWRfYXQYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message pb.Timestamps
 */
export type Timestamps = Message<"pb.Timestamps"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message pb.Timestamps.
 * Use `create(TimestampsSchema)` to create a new message.
 */
export const TimestampsSchema: GenMessage<Timestamps> = /*@__PURE__*/
  messageDesc(file_timestamps, 0);

