// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file topo.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Topogon } from "./topogon_pb";
import { file_topogon } from "./topogon_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file topo.proto.
 */
export const file_topo: GenFile = /*@__PURE__*/
  fileDesc("Cgp0b3BvLnByb3RvEgJwYiJACgRUb3BvEgoKAmlkGAEgASgDEg0KBXRpdGxlGAIgASgJEh0KCHRvcG9nb25zGAMgAygLMgsucGIuVG9wb2dvbkIuWixnaXRodWIuY29tL2dyZWdoYXJ0L2NsaW1iaW5nLWFwcC9pbnRlcm5hbC9wYmIGcHJvdG8z", [file_topogon]);

/**
 * @generated from message pb.Topo
 */
export type Topo = Message<"pb.Topo"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: repeated pb.Topogon topogons = 3;
   */
  topogons: Topogon[];
};

/**
 * Describes the message pb.Topo.
 * Use `create(TopoSchema)` to create a new message.
 */
export const TopoSchema: GenMessage<Topo> = /*@__PURE__*/
  messageDesc(file_topo, 0);

