// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file topogon.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TopogonData } from "./topogon_data_pb";
import { file_topogon_data } from "./topogon_data_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file topogon.proto.
 */
export const file_topogon: GenFile = /*@__PURE__*/
  fileDesc("Cg10b3BvZ29uLnByb3RvEgJwYiKLAQoHVG9wb2dvbhIKCgJpZBgBIAEoAxINCgVsYWJlbBgCIAEoCRIdCgRkYXRhGAMgASgLMg8ucGIuVG9wb2dvbkRhdGESDwoHdG9wb19pZBgEIAEoAxIPCgdhcmVhX2lkGAUgASgDEhIKCmJvdWxkZXJfaWQYBiABKAMSEAoIcm91dGVfaWQYByABKANCLlosZ2l0aHViLmNvbS9ncmVnaGFydC9jbGltYmluZy1hcHAvaW50ZXJuYWwvcGJiBnByb3RvMw", [file_topogon_data]);

/**
 * @generated from message pb.Topogon
 */
export type Topogon = Message<"pb.Topogon"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: pb.TopogonData data = 3;
   */
  data?: TopogonData;

  /**
   * @generated from field: int64 topo_id = 4;
   */
  topoId: bigint;

  /**
   * @generated from field: int64 area_id = 5;
   */
  areaId: bigint;

  /**
   * @generated from field: int64 boulder_id = 6;
   */
  boulderId: bigint;

  /**
   * @generated from field: int64 route_id = 7;
   */
  routeId: bigint;
};

/**
 * Describes the message pb.Topogon.
 * Use `create(TopogonSchema)` to create a new message.
 */
export const TopogonSchema: GenMessage<Topogon> = /*@__PURE__*/
  messageDesc(file_topogon, 0);

