// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file topogon_data.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file topogon_data.proto.
 */
export const file_topogon_data: GenFile = /*@__PURE__*/
  fileDesc("ChJ0b3BvZ29uX2RhdGEucHJvdG8SAnBiIskDCgtUb3BvZ29uRGF0YRInCghwb2x5Z29ucxgBIAMoCzIVLnBiLlRvcG9nb25EYXRhLkxhYmVsEiMKBWxpbmVzGAIgAygLMhQucGIuVG9wb2dvbkRhdGEuTGluZRodCgVQb2ludBIJCgF4GAEgASgBEgkKAXkYAiABKAEaTQoETGluZRIlCgZwb2ludHMYASADKAsyFS5wYi5Ub3BvZ29uRGF0YS5Qb2ludBINCgVjb2xvchgCIAEoCRIPCgd0ZW5zaW9uGAMgASgBGoYBCgVMYWJlbBIMCgR0ZXh0GAEgASgJEiQKBXBvaW50GAIgASgLMhUucGIuVG9wb2dvbkRhdGEuUG9pbnQSDQoFY29sb3IYAyABKAkSDAoEZmlsbBgEIAEoCRIsCglkaXJlY3Rpb24YBSABKA4yGS5wYi5Ub3BvZ29uRGF0YS5EaXJlY3Rpb24idQoJRGlyZWN0aW9uEhkKFURJUkVDVElPTl9VTlNQRUNJRklFRBAAEhAKDERJUkVDVElPTl9VUBABEhMKD0RJUkVDVElPTl9SSUdIVBACEhIKDkRJUkVDVElPTl9ET1dOEAMSEgoORElSRUNUSU9OX0xFRlQQBEIuWixnaXRodWIuY29tL2dyZWdoYXJ0L2NsaW1iaW5nLWFwcC9pbnRlcm5hbC9wYmIGcHJvdG8z");

/**
 * @generated from message pb.TopogonData
 */
export type TopogonData = Message<"pb.TopogonData"> & {
  /**
   * @generated from field: repeated pb.TopogonData.Label polygons = 1;
   */
  polygons: TopogonData_Label[];

  /**
   * @generated from field: repeated pb.TopogonData.Line lines = 2;
   */
  lines: TopogonData_Line[];
};

/**
 * Describes the message pb.TopogonData.
 * Use `create(TopogonDataSchema)` to create a new message.
 */
export const TopogonDataSchema: GenMessage<TopogonData> = /*@__PURE__*/
  messageDesc(file_topogon_data, 0);

/**
 * Sub-messages for internal representation of topogon data.
 *
 * @generated from message pb.TopogonData.Point
 */
export type TopogonData_Point = Message<"pb.TopogonData.Point"> & {
  /**
   * @generated from field: double x = 1;
   */
  x: number;

  /**
   * @generated from field: double y = 2;
   */
  y: number;
};

/**
 * Describes the message pb.TopogonData.Point.
 * Use `create(TopogonData_PointSchema)` to create a new message.
 */
export const TopogonData_PointSchema: GenMessage<TopogonData_Point> = /*@__PURE__*/
  messageDesc(file_topogon_data, 0, 0);

/**
 * @generated from message pb.TopogonData.Line
 */
export type TopogonData_Line = Message<"pb.TopogonData.Line"> & {
  /**
   * @generated from field: repeated pb.TopogonData.Point points = 1;
   */
  points: TopogonData_Point[];

  /**
   * @generated from field: string color = 2;
   */
  color: string;

  /**
   * @generated from field: double tension = 3;
   */
  tension: number;
};

/**
 * Describes the message pb.TopogonData.Line.
 * Use `create(TopogonData_LineSchema)` to create a new message.
 */
export const TopogonData_LineSchema: GenMessage<TopogonData_Line> = /*@__PURE__*/
  messageDesc(file_topogon_data, 0, 1);

/**
 * @generated from message pb.TopogonData.Label
 */
export type TopogonData_Label = Message<"pb.TopogonData.Label"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * @generated from field: pb.TopogonData.Point point = 2;
   */
  point?: TopogonData_Point;

  /**
   * @generated from field: string color = 3;
   */
  color: string;

  /**
   * @generated from field: string fill = 4;
   */
  fill: string;

  /**
   * @generated from field: pb.TopogonData.Direction direction = 5;
   */
  direction: TopogonData_Direction;
};

/**
 * Describes the message pb.TopogonData.Label.
 * Use `create(TopogonData_LabelSchema)` to create a new message.
 */
export const TopogonData_LabelSchema: GenMessage<TopogonData_Label> = /*@__PURE__*/
  messageDesc(file_topogon_data, 0, 2);

/**
 * @generated from enum pb.TopogonData.Direction
 */
export enum TopogonData_Direction {
  /**
   * @generated from enum value: DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIRECTION_UP = 1;
   */
  UP = 1,

  /**
   * @generated from enum value: DIRECTION_RIGHT = 2;
   */
  RIGHT = 2,

  /**
   * @generated from enum value: DIRECTION_DOWN = 3;
   */
  DOWN = 3,

  /**
   * @generated from enum value: DIRECTION_LEFT = 4;
   */
  LEFT = 4,
}

/**
 * Describes the enum pb.TopogonData.Direction.
 */
export const TopogonData_DirectionSchema: GenEnum<TopogonData_Direction> = /*@__PURE__*/
  enumDesc(file_topogon_data, 0, 0);

