// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file trail.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Line } from "./line_pb";
import { file_line } from "./line_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file trail.proto.
 */
export const file_trail: GenFile = /*@__PURE__*/
  fileDesc("Cgt0cmFpbC5wcm90bxICcGIiLAoFVHJhaWwSCgoCaWQYASABKAMSFwoFbGluZXMYAiADKAsyCC5wYi5MaW5lQi5aLGdpdGh1Yi5jb20vZ3JlZ2hhcnQvY2xpbWJpbmctYXBwL2ludGVybmFsL3BiYgZwcm90bzM", [file_line]);

/**
 * @generated from message pb.Trail
 */
export type Trail = Message<"pb.Trail"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: repeated pb.Line lines = 2;
   */
  lines: Line[];
};

/**
 * Describes the message pb.Trail.
 * Use `create(TrailSchema)` to create a new message.
 */
export const TrailSchema: GenMessage<Trail> = /*@__PURE__*/
  messageDesc(file_trail, 0);

