// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file upload.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file upload.proto.
 */
export const file_upload: GenFile = /*@__PURE__*/
  fileDesc("Cgx1cGxvYWQucHJvdG8SAnBiIrIBCgZVcGxvYWQSCgoCaWQYASABKAMSCwoDa2V5GAIgASgJEhEKCWRpcmVjdG9yeRgDIAEoCRIOCgZlbmdpbmUYBCABKAkSFQoNb3JpZ2luYWxfbmFtZRgFIAEoCRIRCglmaWxlX3NpemUYBiABKAMSEQoJc2hhMV9oYXNoGAcgASgJEi8KC3VwbG9hZGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIuWixnaXRodWIuY29tL2dyZWdoYXJ0L2NsaW1iaW5nLWFwcC9pbnRlcm5hbC9wYmIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message pb.Upload
 */
export type Upload = Message<"pb.Upload"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: string directory = 3;
   */
  directory: string;

  /**
   * @generated from field: string engine = 4;
   */
  engine: string;

  /**
   * @generated from field: string original_name = 5;
   */
  originalName: string;

  /**
   * @generated from field: int64 file_size = 6;
   */
  fileSize: bigint;

  /**
   * @generated from field: string sha1_hash = 7;
   */
  sha1Hash: string;

  /**
   * @generated from field: google.protobuf.Timestamp uploaded_at = 8;
   */
  uploadedAt?: Timestamp;
};

/**
 * Describes the message pb.Upload.
 * Use `create(UploadSchema)` to create a new message.
 */
export const UploadSchema: GenMessage<Upload> = /*@__PURE__*/
  messageDesc(file_upload, 0);

