server:
  port: 6001
  cookies:
    secret: 'temposecret8213408SFS@##$'
  sessions:
    secret: develsessionsecret
    prefix: 'apollo|sid|{NODE_ENV}'
  redis:
    host: localhost
    port: 6379
  postgres:
    host: localhost 
    port: 5432
    username: greg
    password: postgrespw
    database: greg
