port: 6001
database:
  sync: true
  postgres:
    host: localhost
    port: 5432
    username: greg
    password: postgrespw
    database: greg
  sqlite:
    database: ./scratch/dev_db.sqlite
swagger:
  host: localhost:3001
  name: Climbing App OpenAPI Documentation
  license: MIT
  basePath: /api
ssr: 
  hydrate: false
power-putty-server: 
  cookies:
    secret: 'temposecret8213408SFS@##$'
    domain: 'localhost'
  sessions:
    secret: develsessionsecret
    prefix: 'apollo|sid|{NODE_ENV}'
    redis:
      host: localhost
      port: 6379
  serving:
    favicon: '/home/greg/Checkouts/climbing-app/static/ico/favicon.ico'
power-putty-io:
  engine: 'local'
  local:
    rootDirectory: '/home/greg/Checkouts/climbing-app/static/uploads'
