swagger: "2.0"
info:
  version: 0.0.0
  title: Climbing App API
  description: Application API for Climbing app.
  contact:
    name: Greg Hart
    email: greg.hart@adcolony.com
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths: {}